### ISSUE TITLE
Adding search to GitHub Pages

### ISSUE THREAD

**Issue by scania-bootstrap** [scania/corporate-ui#102]
Adding free text search functionality to UX Library using for exampel Jekyll Tipue Search or equivalent.

Demo
https://jekylltools.github.io/jekyll-tipue-search/

Code
https://github.com/jekylltools/jekyll-tipue-search

Should be added to this repository:
https://github.com/scania/corporate-ui-docs

Shown using GitHub Pages here;
https://scania.github.io/corporate-ui-docs/

Make it work on one separate search page to start with...for example on this one (mockup):

scania.github.io/corporate-ui-docs/search/

**Comment by mmexvr** [comment]
Added on jira
