### ISSUE TITLE
Nested panels 

### ISSUE THREAD

**Issue by scania-bootstrap** [scania/corporate-ui#11]
Panels can't be nested without loosing look and feel.  This report contains a few of the issues reported in the former Corporate UI Enterprise repository:

Nested panels inherit wrong font-size for .panel-title
https://github.scania.com/Scania/corporate-ui/issues/305

Nested panels are not affected by contextual classes (See #305, a .panel-primary inside of a .panel-default will receive the styling of the parent.)
https://github.scania.com/Scania/corporate-ui/issues/308

Headings inside `.panel-body` are blue
https://github.scania.com/Scania/corporate-ui/issues/299

Please fix them all in once as they are closely related.

The issues are originally reoported by Adam Thorsell and should be communicated with him once the issue is resolved.

https://github.scania.com/athbjj

**Comment by mmexvr** [comment]
https://github.scania.com/Scania/corporate-ui/issues/299

**Comment by mmexvr** [comment]
Fixed
