### ISSUE TITLE
"table-hover" class doesn't work properly on a striped table.

### ISSUE THREAD

**Issue by vamcs** [scania/corporate-ui#110]
**Describe the bug**
When using the class "table-hover" on a table that has the "table-striped" class, the mouse hover highlighting doesn't happen for the blue rows, only the white ones.

**To Reproduce**
1. Create a table with the following classes and a few rows:
```
<table class="table table-hover table-striped">
(...)
```
2. When hovering the mouse over the white rows the highlighting applied and the row turns blue.
3. But when hovering over the blue rows nothing changes.

**Expected behavior**
All rows should be highlighted regardless of their color.

**Screenshots**
![2018-07-30_15-32-51](https://user-images.githubusercontent.com/18034802/43400483-1ca9d910-940e-11e8-9568-f90ab13b737c.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 67.0.3396.99

**Additional context**
Corporate UI version: 3.1.0

**Comment by scania-bootstrap** [comment]
Thanks for reporting. @mmexvr will take care of this ASAP after coming back from vaccationing.

/Jesper

**Comment by mmexvr** [comment]
Solved
