### ISSUE TITLE
Inputs, selects and btn-md should be 42px heigh. So should Select2 and others that align...

### ISSUE THREAD

**Issue by scania-bootstrap** [scania/corporate-ui#112]
Currently, inputs, input-groups, selects and btn-md and nav-pills has been changed from 46px to 42px. Please check so that it lines up with Select2 and other possible elements in the UX Library. @mmexvr knows what already has been merged and can help explain what's need to be done for Select2 (change so it has an height of 42px) and possible other elements.

THUROUGH TESTING FOR FIREFOX, IE11, EDGE, SAFARI, CHROME and iOS as well as Android.

Please!-)

**Comment by scania-bootstrap** [comment]
For example a specific height could be found in rzslider.css (padding needs to be fixed as well):

.app .select2-container .select2-choice {
    **height: 46px;**
    padding: 0 0 0 10px;
    line-height: 50px;
    border: 1px solid transparent;
}

**Comment by yuyo2** [comment]
There is a pull request for this to scania-angular-ui

**Comment by mmexvr** [comment]
Closing this issue for now, inactive
