### ISSUE TITLE
input type checkbox and radio looks weird in mobile view

### ISSUE THREAD

**Issue by scania-bootstrap** [scania/corporate-ui#113]
![unnamed](https://user-images.githubusercontent.com/10209902/43522534-ef482c64-9599-11e8-8625-6bdb640d0e6b.png)

**Comment by yuyo2** [comment]
I have checked this out in chrome dev tools mobile simulation, and on browserstack. And i cant replicate the problem. So i think i need a real device to test on.

**Comment by yuyo2** [comment]
This is only input-group-addon. Working on it.

**Comment by awinny** [comment]
Just some input here: I think it would be good to have a solution that support both the standard bootstrap structure meening no extra "span" as well as the custom styled one when adding a extra "span".

**Comment by mmexvr** [comment]
Solved?

**Comment by yuyo2** [comment]
#338 in corporate ui
#7 in corporate-ui docs

**Comment by scania-bootstrap** [comment]
Fixed in 3.4.0
