### ISSUE TITLE
Scrollbar styling for Select2 is not scoped to Select/Drop down boxes.

### ISSUE THREAD

**Issue by scania-bootstrap** [scania/corporate-ui#116]
In the FMP Build, the code below makes ALL scrollbars to be very narrow and hard to discover. Look at the image below to understand the problem. Source code remains somewhere in FMP, not in Corporate UI. Need to be scoped to the relevant components and signed of by the KS CX Team (contact Peter Pålhman or Jonatan Lidström).

.app .form-control.select2-container {
  padding: 0;
}
.compact .form-control.select2-container {
  padding: 0;
}
.app table .form-control.select2-container {
  padding: 0;
}
::-webkit-scrollbar {
  width: 10px;
  height: 6px;
}
**::-webkit-scrollbar-track {
  background: #ffffff;
  background-clip: content-box;
}
::-webkit-scrollbar-thumb {
  border-radius: 60px;
  background: #f5f5f5;
  border: 3px solid #ffffff;
  height: 5px;
}
::-webkit-scrollbar-thumb:hover {
  background: #f5f5f5;
}**

![image](https://user-images.githubusercontent.com/10209902/43631789-7cf6bdc6-9704-11e8-81a1-1020422f5950.png)

**Comment by yuyo2** [comment]
There is a pull request for this to scania-angular-ui

**Comment by mmexvr** [comment]
This is fixed already? @scania-bootstrap @yuyo2

**Comment by mmexvr** [comment]
#157

**Comment by mohammed-softordi** [comment]
If this is fixed in https://github.com/scania-bootstrap/scania-angular-ui/pull/13, it's been rolled back. Please see the following merge for detail on why: https://github.com/scania-bootstrap/scania-angular-ui/pull/14
