### ISSUE TITLE
Select2 Drop Down is located at the wrong Z-index.

### ISSUE THREAD

**Issue by scania-bootstrap** [scania/corporate-ui#117]
When having the drop down visible and scrolling, the drop down covers other items like the Main Navigation and the Help Tab. Find the correct layer and test on all sections/pages of FMP.

![image](https://user-images.githubusercontent.com/10209902/43632054-44598dd0-9705-11e8-9a58-b545d7775667.png)

![image](https://user-images.githubusercontent.com/10209902/43632086-687f3782-9705-11e8-9c90-00eea873c6a2.png)

**Comment by yuyo2** [comment]
There is a pull request for this to scania-angular-ui

**Comment by mmexvr** [comment]
#157

**Comment by mmexvr** [comment]
Should this be closed?

**Comment by yuyo2** [comment]
Done
