### ISSUE TITLE
Footer: c-corporate-footer still shows a empty container when you don't have any nav-items in mobile

### ISSUE THREAD

**Issue by scania-bootstrap** [scania/corporate-ui#13]
c-corporate-footer still shows a empty container when you don't have any nav-items inside the footer component in mobile-mode in the dropdown.

#288 is related: https://github.scania.com/Scania/corporate-ui/pull/288

![image](https://user-images.githubusercontent.com/10209902/40652209-e8c500a4-6337-11e8-87d4-c4249635f71c.png)

**Comment by awinny** [comment]
Fixed in #17
