### ISSUE TITLE
Table rows are transparent

### ISSUE THREAD

**Issue by adam-scania** [scania/corporate-ui#130]
**Describe the bug**
Table rows are transparent.

**To Reproduce**
```html
<script src="https://d31jnweo1ynb8u.cloudfront.net/build/global/3.1.0-CF/js/corporate-ui.js?preload=false"></script>
<style>
.table-transparent-row-test { background: hotpink; }
</style>
<div class="table-transparent-row-test">
    <table class="table">
        <tbody>
            <tr><td>Row #1</td></tr>
            <tr><td>Row #2</td></tr>
            <tr><td>Row #3</td></tr>
        </tbody>
    </table>
    <table class="table table-striped">
        <tbody>
            <tr><td>Striped row #1</td></tr>
            <tr><td>Striped row #2</td></tr>
            <tr><td>Striped row #3</td></tr>
        </tbody>
    </table>
</div>
```

**Expected behavior**
Rows should have a white background.

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser: Firefox
 - Version: 61

**Comment by scania-bootstrap** [comment]
Tables should be transparent so it can overlay any other background, for example an photograph. It's the Boostrap original implementation. 

Initially, we added .table-panel class to make table background white.
