### ISSUE TITLE
Not enough padding in tables

### ISSUE THREAD

**Issue by adam-scania** [scania/corporate-ui#132]
**Describe the bug**
UX mocks show a lot more table cell padding than CUI.

**Expected behavior**
Looks like the cell padding should be about 20px.

**Comment by mmexvr** [comment]
#153

**Comment by adam-scania** [comment]
I'm not sure this is fixed (in 3.1.4). The table header cells have more padding, but table body cells do not have enough padding.

**Comment by adam-scania** [comment]
@mmexvr

**Comment by adam-scania** [comment]
![table](https://user-images.githubusercontent.com/18661799/45995893-56e2c980-c09a-11e8-860a-448835b4f4d9.png)

**Comment by adam-scania** [comment]
Actual
![table2](https://user-images.githubusercontent.com/18661799/45996036-f43dfd80-c09a-11e8-84cd-1517dae52092.png)

**Comment by scania-bootstrap** [comment]
Use table-lg to get extended padding in table rows.

**Comment by adam-scania** [comment]
That works, thanks.
