### ISSUE TITLE
Default panel headings background color and font family

### ISSUE THREAD

**Issue by adam-scania** [scania/corporate-ui#133]
**Describe the bug**
Default panel headings have the wrong background color (`#e8f0f3`) and font family (`Scania Sans Headline`).

**To Reproduce**
```html
<script src="https://d31jnweo1ynb8u.cloudfront.net/build/global/3.1.0-CF/js/corporate-ui.js?preload=false"></script>
<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Test</h3>
    </div>
</div>
```

**Expected behavior**
Background color should be `#fff` and the font family should be the CUI equivalent of ` Scania Sans Semi Cond Bold`.

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser: Firefox
 - Version: 61

**Comment by mmexvr** [comment]
#151 related with

**Comment by scania-bootstrap** [comment]
Or actually, you'll need to skip that h3 so that you don't end up with Scania Sans Headline:

`<div class="panel panel-default">`
`    <div class="panel-heading light">`
`      <h3>Panel title</h3>`
`    </div>`
`    <div class="panel-body">`
`      Panel content`
`    </div>`
`</div>`
