### ISSUE TITLE
Validation states for Input fields

### ISSUE THREAD

**Issue by scania-bootstrap** [scania/corporate-ui#145]
- Now shadow on the input fields
- Text should always be "Scania Black"
-  Paler validation colors according to this mock (there is similar colors available here:
bg-success-bright
bg-warning-bright
bg-danger-bright
bg-info-bright
https://scania.github.io/corporate-ui-docs/colours/all-colors.html

https://preview.uxpin.com/a15261155751433f4cea83f490a5658bbd36388a#/pages/88035963?mode=cmid

- Add explain text below each field when validation needs to display a “Input field notification”:
https://preview.uxpin.com/a15261155751433f4cea83f490a5658bbd36388a#/pages/84052857?mode=cmid
(kolla under “Input field notification”)

**Comment by mmexvr** [comment]
Clearify what this task is about 

@yuyo2

**Comment by scania-bootstrap** [comment]
I'll fix it.
