### ISSUE TITLE
Labels on radiobuttons and checkboxes should be bold on active

### ISSUE THREAD

**Issue by scania-bootstrap** [scania/corporate-ui#147]
Note: When a checkbox or radio button is selected, labels shoud be BOLD, otherwise not.

Standard Label:

.app label, .app caption {
    font-family: "Scania Sans Semi Condensed";
    font-weight: normal;
    color: #949393;
}

Sample: https://preview.uxpin.com/a15261155751433f4cea83f490a5658bbd36388a#/pages/82666073?mode=cmid

**Comment by yuyo2** [comment]
this is issue #148

**Comment by yuyo2** [comment]
All labels for this regular for now. See #338
