### ISSUE TITLE
Forms issues, need to be monitored and solved.

### ISSUE THREAD

**Issue by scania-bootstrap** [scania/corporate-ui#15]
Martin is main responsible for writing this issue off, once fixed in FMP.

Radio buttons overflow their parent(s) 
https://github.scania.com/Scania/corporate-ui/issues/307

Disabled multiselect (select2) looks all kind of strange
https://github.scania.com/Scania/corporate-ui/issues/306

**Comment by yuyo2** [comment]
fixed
