### ISSUE TITLE
Problem when dynamically adding a component with corporateUI.basecomponent

### ISSUE THREAD

**Issue by mmexvr** [scania/corporate-ui#150]
**Describe the bug**
When corporateUI.basecomponent([alert]) for example is added, it will import main-content component anyway. Samething happeneds if a component doesn't exist

A fallback solution is needed for a component that doesn't exist when using corporateUI.basecomponent

all browsers

**Comment by mmexvr** [comment]
#143

**Comment by mmexvr** [comment]
@awinny solved?

**Comment by awinny** [comment]
This will be solved in: #312
