### ISSUE TITLE
Typography

### ISSUE THREAD

**Issue by scania-bootstrap** [scania/corporate-ui#151]
app H2-H6: Scania Sans Semi Condensed

Headline 1 “APP”: Scania Sans Semi Condensed Bold, 24 px / 32 px (COLOR-PRIMARY)
Paragraph “APP”: Scania Sans Semi Condensed Regular, 14 px / 24 px (COLOR-PRIMARY-04)

Headline 1 “.app article”: Scania Sans Headline Bold, 26 px / 24 px (COLOR-PRIMARY)
Ingress “.app article”: Scania Sans Semi Condensed Regular, 20 px / 30 px (COLOR-PRIMARY-04)
Paragraph “.app article”: Scania Sans Semi Condensed Regular, 16 px / 26 px (COLOR-PRIMARY-04)

Panel header: Scania Sans Headline Bold, 16 px (COLOR-PRIMARY or COLOR-BRAND-02)
Page header: Scania Sans Headline Bold, 16 px (COLOR-PRIMARY)
Page title: Scania Sans Semi Condensed Bold, 16 px (COLOR-PRIMARY)

Button Small: Scania Sans Semi Condensed Bold, 16 px (COLOR-BRAND-02)
Button Default: Scania Sans Semi Condensed Bold, 14 px (COLOR-BRAND-02)
Button Small: Scania Sans Semi Condensed Bold, 12 px (COLOR-BRAND-02)

Labels: Scania Sans Semi Condensed Bold, 12 px (COLOR-GREY7)

Form input: Scania Sans Semi Condensed Regular, 13 px (COLOR-PRIMARY-04)

Text links: Scania Sans Semi Condensed Bold, 12 px (COLOR-INFO)

Table: Scania Sans Semi Condensed Regular, 14 px (COLOR-PRIMARY-04)

Table narrow: Scania Sans Semi Condensed Regular, 12 px (COLOR-PRIMARY-04)

**Comment by mmexvr** [comment]
- [ ] app H2-H6: Scania Sans Semi Condensed

- [ ] Headline 1 “APP”: Scania Sans Semi Condensed Bold, 24 px / 32 px (COLOR-PRIMARY)
- [ ] Paragraph “APP”: Scania Sans Semi Condensed Regular, 14 px / 24 px (COLOR-PRIMARY-04)
- [ ] 
- [ ] Headline 1 “.app article”: Scania Sans Headline Bold, 26 px / 24 px (COLOR-PRIMARY)
- [ ] Ingress “.app article”: Scania Sans Semi Condensed Regular, 20 px / 30 px (COLOR-PRIMARY-04)
- [ ] Paragraph “.app article”: Scania Sans Semi Condensed Regular, 16 px / 26 px (COLOR-PRIMARY-04)

- [ ] Panel header: Scania Sans Headline Bold, 16 px (COLOR-PRIMARY or COLOR-BRAND-02)
- [ ] Page header: Scania Sans Headline Bold, 16 px (COLOR-PRIMARY)
- [ ] Page title: Scania Sans Semi Condensed Bold, 16 px (COLOR-PRIMARY)

- [ ] Button Small: Scania Sans Semi Condensed Bold, 16 px (COLOR-BRAND-02)
- [ ] Button Default: Scania Sans Semi Condensed Bold, 14 px (COLOR-BRAND-02)
- [ ] Button Small: Scania Sans Semi Condensed Bold, 12 px (COLOR-BRAND-02)

- [ ] Labels: Scania Sans Semi Condensed Bold, 12 px (COLOR-GREY7)

- [ ] Form input: Scania Sans Semi Condensed Regular, 13 px (COLOR-PRIMARY-04)

- [ ] Text links: Scania Sans Semi Condensed Bold, 12 px (COLOR-INFO)

- [ ] Table: Scania Sans Semi Condensed Regular, 14 px (COLOR-PRIMARY-04)
- [ ] Table narrow: Scania Sans Semi Condensed Regular, 12 px (COLOR-PRIMARY-04)

**Comment by scania-bootstrap** [comment]
article, .app article {
    text-align: left;
    font-size: 1.8rem;
}

The font-size for App Article should be the same as for .app article p so that <li> etc inherits the same size as the paragraphs, if nothing else is stated.

**Comment by mmexvr** [comment]
Solved, create a new specific issue if there is any problems
