### ISSUE TITLE
Table LG

### ISSUE THREAD

**Issue by scania-bootstrap** [scania/corporate-ui#153]
Add .table-lg tr about 60px height  & Add to documentation at UX Library

Add .table-borderless & Add to documentation at UX Library
https://getbootstrap.com/docs/4.1/content/tables/#borderless-table

**Comment by mmexvr** [comment]
#156

**Comment by mmexvr** [comment]
- [x] borderless
- [ ]  table-lg

**Comment by scania-bootstrap** [comment]
Due to line-height and font-size, the row height ended up on 59px rather than 60px
