### ISSUE TITLE
Select2 Dropdown – visual refinement

### ISSUE THREAD

**Issue by peterpahlman** [scania/corporate-ui#157]
The dropdowns still lack some detailing, so please address the following and also see the UXPin provided below – don't forget to make use of the spec mode.

– The input field itself should be 42 px in height (same height as buttons and filters)
– The text in the input field should be horizontally aligned within the box
– The input field should be set to info-bright when the dropdown is expanded
– Font size should be 14 px in both input field and dropdown list
– The text in the input field should be vertically aligned with the text in the dropdown list
– The horizontal divider lines in the dropdown list should be 1 px
– All text should be Scania Black
– The chevron arrow should be <i class="fal fa-chevron-down"></i> and <i class="fal fa-chevron-up"></i>

https://preview.uxpin.com/a15261155751433f4cea83f490a5658bbd36388a#/pages/82317424?mode=cmid

**Comment by scania-bootstrap** [comment]
Font size in .form-control (in the datepicker) in Corporate UI has to be adjusted to the Select2 input size:
![image](https://user-images.githubusercontent.com/10209902/45206762-1f94b000-b286-11e8-8199-7f09c79465b7.png)

**Comment by mohammed-softordi** [comment]
If this is fixed in https://github.com/scania-bootstrap/scania-angular-ui/pull/13, it's been rolled back. Please see the following merge for detail on why: https://github.com/scania-bootstrap/scania-angular-ui/pull/14

**Comment by mmexvr** [comment]
From our point the visual things are done. Please create a new issue if there is any new things come up
