### ISSUE TITLE
Visual issues with startpage panel footer-links (FMP)

### ISSUE THREAD

**Issue by peterpahlman** [scania/corporate-ui#158]
The text links/icon links in the panel footer are looking weird. Please address the following:

– Text size should be set to 12 px
– Icon should be set to 16 px
– No underline on hover
– When two link objects are next to each other a padding of approx 30 px is needed in between them

See the UXPin link below and please use the spec mode for clarification.
https://preview.uxpin.com/217cc66ba08f1b559d1fbf5faa3dab03de0a847c#/pages/88303901?mode=cmid
_Password: Fleet123_

**Comment by scania-bootstrap** [comment]
Wait for version 3.1.2 where many fixes are.

**Comment by scania-bootstrap** [comment]
Fixed in 3.1.3 should be implemented properly in FMP as class="btn btn-info btn-link".

**Comment by mmexvr** [comment]
Solved
