### ISSUE TITLE
Weird scrollbars in FMP

### ISSUE THREAD

**Issue by peterpahlman** [scania/corporate-ui#159]
There seems to be some kind of a custom scrollbar going on that shouldn't be there. We should only have a custom scrollbar in dropdowns, but not in other content (such as the Vehicles list in FMP's Fleet Position). Could we just have browsers' default scrollbars in all cases where custom bars are not specified by the UX team?

See attached images to see the weirdness.

<img width="130" alt="screen shot 2018-08-29 at 16 41 19" src="https://user-images.githubusercontent.com/42805493/44798185-344fb480-abb1-11e8-8f49-2fb15e0590da.png">
<img width="106" alt="screen shot 2018-08-29 at 17 25 40" src="https://user-images.githubusercontent.com/42805493/44798186-34e84b00-abb1-11e8-89ee-02f465956f6c.png">

**Comment by scania-bootstrap** [comment]
It is fixed in 3.1.2. It was the scrollbars for Multiselect that was not scoped to be used in select2 components only.
