### ISSUE TITLE
Autosave function in FMP profile setting page is breaking the Main menu when language is changed

### ISSUE THREAD

**Issue by eabjcr** [scania/corporate-ui#160]
**Describe the bug**
Autosave function in FMP profile setting page is breaking the Main menu when language is changed

**To Reproduce**
1. Go to FMP profile page
2. Change your set language to something else
4. See error on main Menu.

**Expected behavior**
The menu should be triggered on the language update and get refreshed.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mmexvr** [comment]
@scania-bootstrap @awinny

**Comment by scania-bootstrap** [comment]
I belive @awinny is aware of this.
