### ISSUE TITLE
Set copyright year based on current year from the server. To be done in c-corporate-footer

### ISSUE THREAD

**Issue by scania-bootstrap** [scania/corporate-ui#165]
function getDate(){
  var today = new Date();
  var year = today.getFullYear();
}

getDate();

**Comment by scania-bootstrap** [comment]
![image](https://user-images.githubusercontent.com/10209902/44977460-632aa980-af68-11e8-8a29-a3500ccca6aa.png)

**Comment by mmexvr** [comment]
#166

**Comment by scania-bootstrap** [comment]
Fixed in version 3.1.3
