### ISSUE TITLE
.locked for unaccessable items needs design

### ISSUE THREAD

**Issue by scania-bootstrap** [scania/corporate-ui#178]
![image](https://user-images.githubusercontent.com/10209902/45030246-7febdd80-b04b-11e8-8b7b-36faf3104598.png)

**Comment by peterpahlman** [comment]
See the url below for design refinements for "restricted state", "empty state" and "loading state":
https://preview.uxpin.com/a15261155751433f4cea83f490a5658bbd36388a#/pages/92728676?mode=cmid

**Comment by scania-bootstrap** [comment]
Great! We have a technical solution for this using the .loading and .locked classes and then sending text and icon as a parameter. Anyone who grabs this issue, please´check with me before coding.

**Comment by helloimela** [comment]
We will not add new feature in Corporate UI v3. If a need rises for this design to be implemented, please create a new issue for corporate-ui 4. Thank you!
