### ISSUE TITLE
Remove shadow from .btn:active in  buttons.less

### ISSUE THREAD

**Issue by scania-bootstrap** [scania/corporate-ui#180]
.btn:active, .btn.active {
    background-image: none;
    outline: 0;
    -webkit-box-shadow: inset 0 3px 5px rgba(0, 0, 0, .125);
    box-shadow: inset 0 3px 5px rgba(0, 0, 0, .125);
}

**Comment by mmexvr** [comment]
#183

**Comment by mmexvr** [comment]
Solved
