### ISSUE TITLE
12px font-size in Select2 

### ISSUE THREAD

**Issue by scania-bootstrap** [scania/corporate-ui#184]
.app .select2-container-multi .select2-choices .select2-search-choice {
    padding: 14px 15px 15px 25px;
    margin: 5px 0px 0px 5px;
    font-size: 1.2rem;   SHOULD BE 1.2rem
}

Opacity of hover effect on close icon should be 0.8 not 0.

![image](https://user-images.githubusercontent.com/10209902/45031712-e115b000-b04f-11e8-9cb6-5dc0af4345cc.png)

**Comment by mmexvr** [comment]
#157

**Comment by yuyo2** [comment]
is in #157 . Should be font size 1.4 rem
