### ISSUE TITLE
Find an remove this CSS, or at least scope it.

### ISSUE THREAD

**Issue by scania-bootstrap** [scania/corporate-ui#185]
This is acutally FMP specific.

h3, h4, h5, h6 {
    font-family: "Scania Sans","Open Sans",Arial,sans-serif;
    line-height: 1.1;
    color: #555;
    margin-top: 11px;
    border-bottom: 0;
    padding-bottom: 0;
}

h2, h3 {
    font-weight: 300;
}

h3 {
    font-size: 20px;
}

From this declaration, remove the margin-top description.

.help-button.aside.right .btn .aside-content {
    text-transform: uppercase;
    vertical-align: super;
    color: #fff;
    /* margin-top: 8px; */
    white-space: nowrap;
    padding: 0;
}

**Comment by fomekh** [comment]
the css have been removed and I have done a merge request to cwp/NOE_polymer

**Comment by scania-bootstrap** [comment]
GREAT!
