### ISSUE TITLE
mobile navigation breaks at exactly 991 px

### ISSUE THREAD

**Issue by mmexvr** [scania/corporate-ui#194]
**Describe the bug**
at 991px exactly there is a problem with the mobile navigation

**To Reproduce**
1. open any page 
2. minimize exactly to 991 px

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/35451568/45140853-6d40e800-b1b4-11e8-9def-c39cee42b228.png)

**Desktop (please complete the following information):**
- chrome

**Comment by scania-bootstrap** [comment]
The problem occurs when the font-size in <secondary-items> is bigger than 6px. Try this rule:

secondary-items .form-control {
    font-size: 6px;
}

At this site: https://scania.github.io/corporate-ui-docs/developer/used-vehicles.html

**Comment by mmexvr** [comment]
Solved in 4.0.0
