### ISSUE TITLE
Language specific CSS - learn from Scania.Com

### ISSUE THREAD

**Issue by scania-bootstrap** [scania/corporate-ui#197]
As different languages has taller characters we need to look over how the typography appears in for different countries. Arabic, Spanish, Thai and Swedish are common examples of languages that demands special treatment in CSS.

Here you'll find what's implemented at Scania.Com:
https://static.scania.com/development/global/css/languages.css

**Comment by mmexvr** [comment]
#263

**Comment by mmexvr** [comment]
Added on jira
