### ISSUE TITLE
Adding optional hyphenation to Corporate UI

### ISSUE THREAD

**Issue by scania-bootstrap** [scania/corporate-ui#198]
Learn from Scania.Com at:
https://static.scania.com/build/users/aem/global-tweaks/aem.js

**Comment by helloimela** [comment]
We will not add new feature to corporate-ui 3. If problem or requirement arises regarding to this feature, please create a new issue for corporate-ui 4. Since this issue was here from 2018 and there is no clear information what is this about and how to proceed forward, we will close it now.
