### ISSUE TITLE
Add Styling for table-expandable class

### ISSUE THREAD

**Issue by scania-bootstrap** [scania/corporate-ui#200]
Suggested solution
https://mottie.github.io/tablesorter/docs/example-child-rows.html

Implement sample here:
https://scania.github.io/corporate-ui-docs/developer/extended-tables.html

According to this mock:
https://preview.uxpin.com/a15261155751433f4cea83f490a5658bbd36388a#/pages/87428128/specification/no-panels?mode=cmid

**Comment by helloimela** [comment]
We will not add new feature to corporate-ui 3. If needed arise for this design to be implemented, we will add it in corporate-ui 4.

**Comment by helloimela** [comment]
Issue will be closed due to inactivity. New features for design system will be added in version 4.
