### ISSUE TITLE
Design tweaking on input fields ("validation states")

### ISSUE THREAD

**Issue by peterpahlman** [scania/corporate-ui#201]
Input form fields with success/warning/error (the ones that are called "Validation states" in UX Library) has incorrect colors. This is what they should look like:

**Success**
Font color: #44A878 
Border color: #44A878 
BG color: #F2F9F5 

**Warning**
Font color: #F2855F 
Border color: #F2855F 
BG color: #FEF6F4 

**Alert**
Font color: ##CC1040 
Border color: ##CC1040 
BG color: #FAEEED

**Comment by scania-bootstrap** [comment]
![image](https://user-images.githubusercontent.com/10209902/45155639-f0296900-b1db-11e8-8c67-66022d7e8054.png)

**Comment by scania-bootstrap** [comment]
![image](https://user-images.githubusercontent.com/10209902/45156853-a80c4580-b1df-11e8-831c-35fcb37ac596.png)

**Comment by scania-bootstrap** [comment]
![image](https://user-images.githubusercontent.com/10209902/45156874-b6f2f800-b1df-11e8-8ec6-cf78257e265a.png)

**Comment by mmexvr** [comment]
- Should input in focus have the same border color as non focused input ? Same question with the focused background color of the input

![image](https://user-images.githubusercontent.com/35451568/45220405-4e268100-b2ae-11e8-8059-4a01fefe5459.png)

- Label attached to the input should that have the same font color as the input placeholder  

![image](https://user-images.githubusercontent.com/35451568/45220386-3ea73800-b2ae-11e8-8557-c5bd65c93a26.png)

**Comment by peterpahlman** [comment]
Input in focus should be border: 4A8BA4 (info) and fill: F6F9FA (info-bright). See here:
https://preview.uxpin.com/a15261155751433f4cea83f490a5658bbd36388a#/pages/88035963?mode=cmid

**Comment by mmexvr** [comment]
Perfect, will look into it, thanks

**Comment by mmexvr** [comment]
#217

**Comment by mmexvr** [comment]
Is merged, undergoing review

**Comment by mmexvr** [comment]
#225

**Comment by mmexvr** [comment]
in 3.2.0
