### ISSUE TITLE
Bugs in the More functionality

### ISSUE THREAD

**Issue by scania-bootstrap** [scania/corporate-ui#202]
At full browser width (all items visible)
![image](https://user-images.githubusercontent.com/10209902/45153642-04b63300-b1d5-11e8-949f-1d9029adae5b.png)

At 1808px browser width (Glitch). More images below this one as well.
![image](https://user-images.githubusercontent.com/10209902/45153747-5ced3500-b1d5-11e8-9267-fa6c78c0d91a.png)

At 1738px browser width both VEHICLE PERFORMANCE and
TRANSPORTPLANERING has been placed in the More dropdown. shouldn't one be enough?
![image](https://user-images.githubusercontent.com/10209902/45153854-cbca8e00-b1d5-11e8-9f3d-b5c923b8a496.png)

**Comment by mmexvr** [comment]
#175 related

**Comment by awinny** [comment]
This should be solved in latest release.
