### ISSUE TITLE
Color styling on default and disabled inputs

### ISSUE THREAD

**Issue by peterpahlman** [scania/corporate-ui#204]
Default and disabled inputs should be styled according to UXPin:
https://preview.uxpin.com/a15261155751433f4cea83f490a5658bbd36388a#/pages/88035963?mode=cmid

This same styling should also be implemented on dropdown forms, filter forms and datepicker forms – all in accordance to the mockup.

**Default**
Fill: #F0F0F0 
Stroke (1 px): #E2E2E2 
Default text: #94999D
Input text: #53565A 

**Disabled**
Fill: #F7F7F7
No stroke
Default text: #94999D / 80% alpha

**Comment by helloimela** [comment]
#222

**Comment by helloimela** [comment]
Merged to the master, ongoing review

**Comment by mmexvr** [comment]
In 3.2.0
