### ISSUE TITLE
Integrate User Menu and Administration menu into Corporate UI.

### ISSUE THREAD

**Issue by scania-bootstrap** [scania/corporate-ui#213]
Both for Mobile and Desktop. It's the 2 drop down menus on the very right on the main navigation. In FMP. Feel free to create new markup and CSS. 

Perhaps as a StencilJS component?

Here's the current quick fix code from corporate-ui.css (below) and there are underlaying FMP CSS as well:
https://fmp-dev.cw.csawsdev.net/polymer-corporate-cleaning/index.html#/service-planning/to-do/inspection-plans

/*
 * Styles for the user account section in the main navigation
 *
 */

.select-staff-picture .staff-image-container {
  margin-right: 25px;
}

.user-account-menu > div a {
    padding: 10px;
}

.user-account-menu>div .user-name {
    color: #fafafa;
    text-transform: initial;
    word-break: initial;
    white-space: nowrap;
    overflow: hidden;
    padding-right: 10px;
    text-align: right;
}

.user-account-menu .staff-badge {
  width: 32px;
  height: 32px;
}

.navbar-right ul.dropdown-menu {
  width: 194px;
  margin: 0;
  text-align: right;
}
.navbar-right ul.dropdown-menu li a {
  text-transform: none;
}

.navbar-right ul.dropdown-menu li > a:hover,
.navbar-right ul.dropdown-menu li > a:focus {
  background-color: transparent;
}

.navbar-right .services + ul.dropdown-menu {
  width: 194px;
  margin: 0;
}
.navbar-right .user-account-menu + ul.dropdown-menu {
  width: 220px;
  margin: 0;
}

**Comment by awinny** [comment]
"Administration menu into" This should work using a standard bootstrap dropdown.
It has been added to the data pattern in main navigation for secondary-items

**Comment by awinny** [comment]
I think we can close this issue and create a new feature request for a "user component" right @scania-bootstrap ?

**Comment by scania-bootstrap** [comment]
OK!
