### ISSUE TITLE
Colors in Form Control and Select 2 differs

### ISSUE THREAD

**Issue by scania-bootstrap** [scania/corporate-ui#214]
Common text color in inputs should be #242424    PETER?

Current text colors are  HEX #999 in Select2
And for Form Control (inputs, select etc) it's HEX #747472

**Comment by peterpahlman** [comment]
I think we should try #53565A since that is the default text color. Perhaps we find it too light, but worth trying out before making any conclusions.

**Comment by mmexvr** [comment]
#157 related

**Comment by mmexvr** [comment]
Done - @yuyo2

**Comment by yuyo2** [comment]
available in version 3.3.0
