### ISSUE TITLE
Multiple <select> has background: url()

### ISSUE THREAD

**Issue by furkick** [scania/corporate-ui#220]
**Describe the bug**
If using a `<select multiple>`and using a larger number of items the` background: URL()` set in `.select.form-control ` looks odd/don't think it should be there.

**To Reproduce**
1. Create a `<select multiple class="form-control">`
2. Set the height to a larger size. E.g. 500px.
3. See error.

**Expected behavior**
No bold arrow to be shown.

**Screenshots**
![image](https://user-images.githubusercontent.com/7430414/45433462-1bacc780-b6a4-11e8-80c2-033158193553.png)

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome 
 - Version: Version 68.0.3440.106 (Official Build) (64-bit)

**Comment by mmexvr** [comment]
#157

**Comment by yuyo2** [comment]
This one is fixed.
