### ISSUE TITLE
Wrong colors in labels

### ISSUE THREAD

**Issue by peterpahlman** [scania/corporate-ui#221]
Labels "Available variations" have wrong colors. Should be the same colors that are used in buttons.
<img width="1107" alt="screen shot 2018-09-11 at 15 58 29" src="https://user-images.githubusercontent.com/42805493/45433852-5830f100-b6ad-11e8-86e6-8404b2ac085b.png">

**Comment by mmexvr** [comment]
Merged, under review

**Comment by mmexvr** [comment]
#235

**Comment by mmexvr** [comment]
in 3.2.1
