### ISSUE TITLE
Different designs for input/form field

### ISSUE THREAD

**Issue by peterpahlman** [scania/corporate-ui#225]
Input fields/form fields looks different if you go via the "Bootstrap CSS" link than if you go via the "Bootstrap Components" link. Make sure that they are aligned everywhere with the UXPin guidelines:
https://preview.uxpin.com/a15261155751433f4cea83f490a5658bbd36388a#/pages/88035963?mode=cmid

**Please note that "read only" design is a new addition.**

**Comment by mmexvr** [comment]
#157 select2

**Comment by yuyo2** [comment]
Fixed in #157
