### ISSUE TITLE
Weird mouseover colors on buttons

### ISSUE THREAD

**Issue by peterpahlman** [scania/corporate-ui#232]
The mouseover colouring should be set as a fixed value (i.e add 10% white on hover) but now it seems that every color has a different value – especially the primary button seems to have an entirely different hex value.

In my opinion we _could_ have two hex colors per button and that would also give a bit more visual control, but I guess it's easier to just have a global "add 10 % white" rule. Let me know what you prefer from a tech perspective.

**Comment by mmexvr** [comment]
#234 
#233

**Comment by peterpahlman** [comment]
Are we 100% certain that the lighten-rule is applied on primary as well? The color change is sooo noticeable particularly on primary,  instead of just being a subtle visual guidance.  **Can we change to lighten: 5% instead?**

When it comes to the default button I _still_ think it should be a classic ghost button with a BG color only on hover _(try hovering on the buttons)_: https://preview.uxpin.com/a15261155751433f4cea83f490a5658bbd36388a#/pages/84316891?mode=cmid

Another option would be two increase the stroke to 2px (on default) during hover, but that would probably result in the text "jumping".

**Comment by scania-bootstrap** [comment]
Implemented in version 3.2.1
