### ISSUE TITLE
Extra small buttons

### ISSUE THREAD

**Issue by peterpahlman** [scania/corporate-ui#234]
The way text is rendered in both Safari and Chrome (especially Chrome) I think we would need to adjust the padding a bit.

**I'd suggest padding: 2px 8 px 1 px.**

**Comment by scania-bootstrap** [comment]
I'll start with this one.

**Comment by mmexvr** [comment]
#233 
#232 

Related

**Comment by scania-bootstrap** [comment]
Button spacing fixes is now a pull request: #242

**Comment by scania-bootstrap** [comment]
Released in version 3.2.1
