### ISSUE TITLE
Labels: Tweaking needed

### ISSUE THREAD

**Issue by peterpahlman** [scania/corporate-ui#235]
The different sizes of labels differ too much when it comes to how the radius is rendered, and they should also be set with a fixed width. Could we try to follow the specifications below? Also see UXPin for clarification: https://preview.uxpin.com/a15261155751433f4cea83f490a5658bbd36388a#/pages/93344068?mode=cmid

**label-lg**
Height: 42 px / Fixed min width: 144 px / Radius: 22 px / Font size: 14 px

**label-default**
Height: 30 px / Fixed min width: 128 px / Radius: 16 px /  Font size: 12 px

**label-sm**
Height: 24 px / Fixed min width: 104 px / Radius: 14 px /  Font size: 10 px

**Comment by scania-bootstrap** [comment]
In this pull request: Labels and badges #311

**Comment by scania-bootstrap** [comment]
Available in version Corporate UI 3.4.0
