### ISSUE TITLE
Badges styling

### ISSUE THREAD

**Issue by peterpahlman** [scania/corporate-ui#236]
Badges need a restyling according to UXPin:
https://preview.uxpin.com/a15261155751433f4cea83f490a5658bbd36388a#/pages/93344068?mode=cmid

**Badges with one digit**
Circle: 24 px / Font size: 12 px

**Badges with multiple digits**
Height: 24 px / Side padding: 10 px / Radius: 12 px /  Font size: 12 px

**Comment by scania-bootstrap** [comment]
Using CSS I don't think we cannot decide if there is one or more digits within a badge.  Using logic for badges we could add rules for one digit badges but it's a kind of dirty to do that. Best if we can find one rule for both scenarios. Having "a crawler" looking all over the DOM for a badge with one character, on every single event, might be a really bad solution...

Although, we could introduce Bootstrap 4 "badge-pills" for use when we need more rounded badges:

http://getbootstrap.com/docs/4.1/components/badge/#pill-badges

**Comment by scania-bootstrap** [comment]
As badges are often used on buttons, in lists etc this default badge would destroy the specifications for many elements. Can we turn it around so that it's badge-lg and badge? Pictured below:

![image](https://user-images.githubusercontent.com/10209902/45943976-c8fad600-bfe8-11e8-8d2a-c997452f15d7.png)

**Comment by scania-bootstrap** [comment]
Suggested default measures:

padding: 4px 6px;
font-size: 12px;
border-radius: 12px;

As this:

![image](https://user-images.githubusercontent.com/10209902/45944132-5807ee00-bfe9-11e8-9599-b7781e780a3b.png)

**Comment by scania-bootstrap** [comment]
Labels on the other hand side is basing its measures on the parent element as they are using percentage and em as they calculate what size they're going to get:

.label {
    margin-bottom: 1px;
    font-size: 80%;
    font-weight: bold;
    border-radius: 1em;
    padding: 0.5em 1.9em 0.6em;
    display: inline-block;
}

**Comment by scania-bootstrap** [comment]
If we can do adjustments to current radius and padding, that would be great.

**Comment by mmexvr** [comment]
#235 related

**Comment by scania-bootstrap** [comment]
Now in the pipe to be built: Labels and badges #311

**Comment by scania-bootstrap** [comment]
Available in version Corporate UI 3.4.0
