### ISSUE TITLE
Sub navigation appearance changes when parent nav-item is hidden and then shown

### ISSUE THREAD

**Issue by shaheer-scania** [scania/corporate-ui#24]
Sub navigation appearance changes when parent nav-item is hidden and then shown

**To Reproduce**

1. Add sub navigation menu
2. The sub navigation is shown properly 
3. Hide parent nav-item (for example: when user login)
4. Show parent nav-item (for example: when user logout) 
5. The appearance changes, and not same as seen in step-2

version: 2.5.0

**Comment by awinny** [comment]
@shaheer-scania Is there a file in our examples that can replicate this issue?

**Comment by shaheer-scania** [comment]
How to replicate:
1. Goto https://developer.test.cs.scania.com/
2. Click on *Get Started* menu
3. Note down the Sub menus
4. Now login 
5. *Get started* menu will disappear
6. Now LOG OUT
7. *Get started* menu will re-appear
8. Now see the sub menus. Its different from than as you see in step-3

**Comment by shaheer-scania** [comment]
@awinny

**Comment by awinny** [comment]
@shaheer-scania Im not able to login and there by cant reproduce this issue.
Hoever if the nav-item have a class active or a attribute active set to true, this item will show its chilldrens. So simply set active to false or remove the active class to hide its chilldrens

**Comment by awinny** [comment]
Closed for not, if the issue still exist please reopen.
