### ISSUE TITLE
Selected table rows should be blue with a blue border

### ISSUE THREAD

**Issue by adam-scania** [scania/corporate-ui#247]
**Describe the bug**
The selected row does not have a blue background with blue borders.

**To Reproduce**
```
<script src="https://d31jnweo1ynb8u.cloudfront.net/build/global/3.1.4-CF/js/corporate-ui.js?preload=false"></script>
<table class="table">
    <tbody>
        <tr><td>Row #1</td></tr>
        <tr class="active"><td>Row #2 (active)</td></tr>
        <tr><td>Row #3</td></tr>
        <tr><td>Row #4</td></tr>
        <tr><td>Row #5</td></tr>
    </tbody>
</table>
```

**Expected behavior**
The selected row should have a blue background and a blue border.

**Screenshots**
It should look like this.
![table](https://user-images.githubusercontent.com/18661799/45995934-8c87b280-c09a-11e8-8acd-827cf2f0c336.png)

**Comment by mmexvr** [comment]
<table class="table table-striped table-selectable">

**Comment by scania-bootstrap** [comment]
And table-lg. 

table class="table table-striped table-selectable table-lg"

https://scania.github.io/corporate-ui-docs/developer/extended-tables.html

**Comment by scania-bootstrap** [comment]
Note that several things have changed in that mockup, for example the TH are no longer uppercase and the font are not condensed rather than Scania Sans Semi Condensed. There is also a grey border around the table.

Just so that you know.

**Comment by adam-scania** [comment]
The issue appears with this combination of classes:

´´´
<script src="https://d31jnweo1ynb8u.cloudfront.net/build/global/3.1.4-CF/js/corporate-ui.js?preload=false"></script>
<table class="table table-lg table-panel table-striped table-hover table-selectable">
    <tbody>
        <tr><td>Row #1</td></tr>
        <tr class="active"><td>Row #2 (active)</td></tr>
        <tr><td>Row #3</td></tr>
        <tr><td>Row #4</td></tr>
        <tr><td>Row #5</td></tr>
    </tbody>
</table>
´´´

**Comment by adam-scania** [comment]
![table](https://user-images.githubusercontent.com/18661799/46001682-2e63cb00-c0ac-11e8-866e-dd1e2329f09a.png)

**Comment by scania-bootstrap** [comment]
@mmexvr kollar du på detta särfall?

![image](https://user-images.githubusercontent.com/10209902/46002789-44bf5600-c0af-11e8-812f-fdee5ba212f7.png)

**Comment by scania-bootstrap** [comment]
We're adding border-collapse: collapse; to table-panel (do you need that class when you have table-lg?) and I have added it to corporate-ui.css (fmp) for you to test. REEEELOAD.

**Comment by scania-bootstrap** [comment]
Added active to the extended-tables.html samples page (Firefox screen shot), with collapsed borders:

![image](https://user-images.githubusercontent.com/10209902/46006760-8ef90500-c0b8-11e8-8cb9-8097f1aa93e1.png)

https://scania.github.io/corporate-ui-docs/developer/extended-tables.html

**Comment by scania-bootstrap** [comment]
@adam-scania is this issue sorted out or should we keep it open?

**Comment by adam-scania** [comment]
Which version is it supposed to work on?

**Comment by scania-bootstrap** [comment]
3.2.1 (and fix are also in FMP corporate-ui.css)


https://scania.github.io/corporate-ui-docs/developer/extended-tables.html

![image](https://user-images.githubusercontent.com/10209902/46139344-981bda80-c24e-11e8-8b15-33aa3248fd92.png)

**Comment by adam-scania** [comment]
Yeah it seems to work in 3.2.1.
