### ISSUE TITLE
When clicking the more dropdown (active) it change position in IE

### ISSUE THREAD

**Issue by mmexvr** [scania/corporate-ui#250]
**Describe the bug**
#248 related pull-request
Issue with the more function in IE 11

1. When clicking the more dropdown (active) It change position
2. Styling of more dropdown is different from the rest of the nav-item, underline for example

![image](https://user-images.githubusercontent.com/35451568/46012904-e56f3f00-c0ca-11e8-8f65-08ede79993c9.png)

**Comment by awinny** [comment]
This has been fixed and is available in the latest version.

**Comment by scania-bootstrap** [comment]
This has been fixed and is available in version 3.3.0.

Latest version will differ depending on when I read this thread!-)
