### ISSUE TITLE
active nav-item in secondary-items does not get deactivated when clicking another item within the primary items.

### ISSUE THREAD

**Issue by scania-bootstrap** [scania/corporate-ui#252]
Senario:

Clicked on "Support" (more images below):

![image](https://user-images.githubusercontent.com/10209902/46013865-c1f9c380-c0cd-11e8-9c07-b77472289ff8.png)

Clicked "Log in"

![image](https://user-images.githubusercontent.com/10209902/46013893-d0e07600-c0cd-11e8-8583-07ff60407acf.png)

And now, clicking "Support" again, "Log in" still has the active class on it.

![image](https://user-images.githubusercontent.com/10209902/46013946-f8374300-c0cd-11e8-8b11-0c0707d7e7f0.png)

**Comment by shaheer-scania** [comment]
It is actually an issue on application side. Please close this
