### ISSUE TITLE
White text on white input fields

### ISSUE THREAD

**Issue by peterpahlman** [scania/corporate-ui#254]
White input fields on dark backgrounds seem to get a white font. See actual issue report here:
https://jira.scania.com/browse/FMS-26515

**Comment by mmexvr** [comment]
If we put jira cases from project, everyone at corporate team needs access to the jira.

@scania-bootstrap 
@peterpahlman

**Comment by peterpahlman** [comment]
Unfortunately (or luckily) there isn't that much info in the Jira issue itself, but see the image attached to see where the problem occurs.
<img width="1495" alt="screenshot 2018-09-26 at 16 11 30" src="https://user-images.githubusercontent.com/42805493/46085727-f4c3ba80-c1a6-11e8-8102-52b40ce75ef2.png">

**Comment by scania-bootstrap** [comment]
Available in version 3.3.0
