### ISSUE TITLE
<td>s in <thead> are smaller than <th>s

### ISSUE THREAD

**Issue by adam-scania** [scania/corporate-ui#258]
**Describe the bug**
`<td>` in `<thead>` does not have the same 1px border as `<th>` does. This makes the `<td>` appear smaller when stacked on top of a `<th>`.

**To Reproduce**
```
<script src="https://d31jnweo1ynb8u.cloudfront.net/build/global/3.2.1-CF/js/corporate-ui.js?preload=false"></script>
<style>
.thead-td-test {
    width: 400px;
    margin: 0 auto;
}
</style>
<div class="app thead-td-test">
    <table class="table">
        <thead>
            <tr>
                <td>Table data in table head</td>
            </tr>
            <tr>
                <th>Table header in table head</th>
            </tr>
        </thead>
    </table>
</div>
```

**Expected behavior**
`<td>`s and `<th>`s should have the same size in `<thead>`.

**Screenshots**
![thead-td](https://user-images.githubusercontent.com/18661799/46143400-1c278f80-c25a-11e8-816f-e8c5e05f27eb.png)

**Comment by mmexvr** [comment]
3.3.0
