### ISSUE TITLE
Labels in table heads are hard to read

### ISSUE THREAD

**Issue by adam-scania** [scania/corporate-ui#260]
**Describe the bug**
`<label>`s are gray in `<thead>`s, and the contrast to the background color is very low. Hard to read. Also maybe the label isn't perfectly aligned with the checkbox, I don't know.

**To Reproduce**
```
<script src="https://d31jnweo1ynb8u.cloudfront.net/build/global/3.2.0-CF/js/corporate-ui.js?preload=false"></script>
<style>
.thead-checkbox-text {
    width: 400px;
    margin: 0 auto;
}
</style>
<div class="app thead-checkbox-text">
    <table class="table">
        <thead>
            <tr>
                <td>
                    <div class="checkbox">
                        <label>
                            <input type="checkbox">
                            <span></span>
                            <span>Label text</span>
                        </label>
                    </div>
                </td>
            </tr>
        </thead>
    </table>
</div>
```

**Expected behavior**
White perhaps

**Screenshots**
![thead-checkbox](https://user-images.githubusercontent.com/18661799/46143438-3e211200-c25a-11e8-88f0-290bbaf96f1b.png)

**Comment by adam-scania** [comment]
The checkbox background color should also be lighter, maybe

**Comment by scania-bootstrap** [comment]
Checkbox and Radio Lables are now sensitive to what background they are placed at. If a dark colour is specified, the label should be white, try to add table-primary to the table classes and you'll see.
For the acutal checkbox or radiobutton please add:
<input type="checkbox" class="radio-checkbox-inverse">

Not a very pretty solution but it's a mix of custom radiochecks, inverted colours and scope creep!-)

**Comment by scania-bootstrap** [comment]
@adam-scania try this code:

```
<div class="app">
    <table class="table table-primary">
        <thead>
            <tr>
                <td>
                    <div class="checkbox">
                        <label>
                            <input type="checkbox" class="radio-checkbox-inverse">
                            <span></span>
                            <span>Label text</span>
                        </label>
                    </div>
                </td>
            </tr>
        </thead>
    </table>
</div>
```

**Comment by scania-bootstrap** [comment]
Please re-open if it does not work out.

**Comment by scania-bootstrap** [comment]
@yuyo2 it would be nice if the rule for the inverted label is applied to the checkbox/radio button itself, then the extra class on the input field wouldn't be mandatory.
