### ISSUE TITLE
Small screen/mobile design for c-page-header

### ISSUE THREAD

**Issue by adam-scania** [scania/corporate-ui#271]
**Is your feature request related to a problem? Please describe.**
It looks weird on iPhone and similar devices. There need to be vertical spacing between filters/controls, buttons need to be left aligned and the subheading should appear on a new line without a separator.

**Describe the solution you'd like**
![mobile-c-page-header-1](https://user-images.githubusercontent.com/18661799/46462761-9019e880-c7c2-11e8-9620-a4cccb547124.png)
![mobile-c-page-header-2](https://user-images.githubusercontent.com/18661799/46462762-9019e880-c7c2-11e8-9dbf-8fb7327b877c.png)

**Comment by adam-scania** [comment]
Duplicate https://github.com/scania/corporate-ui/issues/273

**Comment by scania-bootstrap** [comment]
But with detailed alignments of spacings etc.

**Comment by scania-bootstrap** [comment]
Pull request for first iteration available here:  #274

**Comment by mmexvr** [comment]
3.3.0
