### ISSUE TITLE
Mobile Layout of c-page-header

### ISSUE THREAD

**Issue by scania-bootstrap** [scania/corporate-ui#273]
https://preview.uxpin.com/6c7da7792454c9bd5c90d59a3a410c99d8c01c4f#/pages/92370410/simulate/no-panels?mode=cmid

Although, it looks like moving things around might require some change in the logic but we'll have a look at it.

Grid order for current desktop version:

Text header 
Buttons
Input fields
Nav pills 

Suggested order for current mobile version:

Nav pills 
Text header 
Buttons
Input fields

Pictured below you'll find the "easy" way that requires CSS changes only.

![image](https://user-images.githubusercontent.com/10209902/46467243-8d70c080-c7cd-11e8-869e-82c72fe776e8.png)

**Comment by adam-scania** [comment]
Duplicate https://github.com/scania/corporate-ui/issues/271

**Comment by scania-bootstrap** [comment]
Duplicate #271
