### ISSUE TITLE
Staff-badge

### ISSUE THREAD

**Issue by fomekh** [scania/corporate-ui#296]
**Version of 3.3.0**<br/>

**Describe the bug**<br/>
User initial are not vertical middle.

![bug_staff](https://user-images.githubusercontent.com/6946108/46677141-4e35db80-cbe2-11e8-906c-edcfe1afc2cd.PNG)
![bug_staff2](https://user-images.githubusercontent.com/6946108/46677146-50983580-cbe2-11e8-8bd3-58c840ad85a7.PNG)

**Comment by fomekh** [comment]
Remove: !important and set padding: 6px 0 based on height: 32px; width: 32px;

**Comment by scania-bootstrap** [comment]
They should be integrated and perhaps be a part of Corporate UI, earlier report can be found here:
Integrate User Menu and Administration menu into Corporate UI. #213
