### ISSUE TITLE
Custom Components - Documentation missing in UX Library

### ISSUE THREAD

**Issue by scania-bootstrap** [scania/corporate-ui#297]
- [x]   - APP vs PUBLIC (DONE)
- [x]   - Modals: XL, XXL, fullscreen, y-scroll and modal-article  (DONE)
- [x]   - Bootstrap 3 vs Bootstrap 4  (DONE)
- [x]   - Bootstrap Cards  (DONE)
- [x]   - Labels & Badges update  (DONE)
- [x]   - Alert Indicators  (DONE)
- [x]   - Modal  (DONE)
- [x]   - Z-Index  (DONE)
- [x]   - Spacing & Utilities from Bootstrap 4  (DONE)

- [ ]   - Header c-page-header
- [ ]   - Templates for page layouts
- [x]   - Form with select2
- [ ]   - Loading icon
- [x]   - Dealer Header Code Generator
- [ ]   - Data Env
- [ ]   - Container Flex
- [ ]   - Tablesorter

**Comment by mmexvr** [comment]
#94
