### ISSUE TITLE
Scrollwheel on mouse is not working on modal box

### ISSUE THREAD

**Issue by helloimela** [scania/corporate-ui#366]
**Version of Corporate-ui**<br/>
3.4.0

**Describe the bug**<br/>
Scroll is not triggered when modal box is opened. 

**To Reproduce**<br/>
1. Go to https://scania.github.io/corporate-ui-docs/developer/bootstrap-original-docs.html > Bootstrap Javascript > Modal > Scroll to Live Demo
2. Click on Launch Demo Modal
3. Scroll the page with mouse scroll
4. Expected behaviour is not occured

**Expected behavior**<br/>
Should scroll the page

**Desktop (please complete the following information):**<br/>
 - OS: Windows
 - Browser Chrome

**Comment by helloimela** [comment]
@scania-bootstrap I check this issue, reproduced it in several different environments and found this quick fix for the mouse scrolling issue. Need to check in safari though. Works fine in chrome, mozilla, and IE with this quick fix.

[added in ux library inline html style]

.modal.fade.in {
    transform: translateZ(0);
    -webkit-transform: translateZ(0);
}
https://github.com/twbs/bootstrap/issues/16297

**Comment by scania-bootstrap** [comment]
Great! Safari didn’t have the issue in the first place so it’s perfect!

/Jesper

**Comment by helloimela** [comment]
@scania-bootstrap I don't have write access to the docs repo, so I created a pull request there :)
https://github.com/scania/corporate-ui-docs/pull/9

**Comment by helloimela** [comment]
Merged in UX Library https://github.com/scania/corporate-ui-docs/pull/9
