### ISSUE TITLE
Popover and tooltips event not working on modal box

### ISSUE THREAD

**Issue by helloimela** [scania/corporate-ui#369]
**Version of Corporate-ui**<br/>
3.4.0

**Describe the bug**<br/>
Popover in a modal
 This  should trigger a popover on click.  

Tooltips in a modal 
This link and that link should have tooltips on hover.

**To Reproduce**<br/>
1. Go to https://scania.github.io/corporate-ui-docs/developer/bootstrap-original-docs.html > Bootstrap 2. Javascript > Modal > Scroll to Live Demo
3. Click on Launch Demo Modal
4. Click on button and tooltips link
5. Expected behaviour is not occured

**Browser**
Chrome on Windows OS

**Comment by yuyo2** [comment]
Checked this. It seems to work fine now
