### ISSUE TITLE
Mobile menu scrolls when scrolling in Desktop mode, and then goes to mobile.

### ISSUE THREAD

**Issue by scania-bootstrap** [scania/corporate-ui#38]
**Describe the bug**
Mobile menu scrolls when scrolling in Desktop mode, and then goes to mobile. 

To Reproduce at https://scania.github.io/corporate-ui-docs/
1 Scrolla ner på sidan.
2 Dra ihop skärmen så att hamburgaren visas.
3 Klicka på burgaren...

**Expected behavior**
All items should be visible.

![image](https://user-images.githubusercontent.com/10209902/40981590-9965695a-68db-11e8-9fe3-ef1d61f1871f.png)
![image](https://user-images.githubusercontent.com/10209902/40981628-ab03eb5a-68db-11e8-9aea-0350954adbe7.png)

**Comment by mmexvr** [comment]
@awinny Done?
