### ISSUE TITLE
Highchart

### ISSUE THREAD

**Issue by sssaff** [scania/corporate-ui#39]
**Describe the bug**
Error message:
Unhandled exception at line 10, column 43 in https://static.scania.com/vendors/components/pure-js/highcharts/5.0.7/code/highcharts.js
0x800a139e - Körningsfel i JavaScript: Highcharts error #17: www.highcharts.com/errors/17

**To Reproduce**
Trying to create a graph with following example:
https://www.highcharts.com/demo/arearange-line

**Screenshots**

**Desktop (please complete the following information):**
Doesn't matter what browser.

**Smartphone (please complete the following information):**
-

**Additional context**

**Comment by sssaff** [comment]
Solved it by myself. It appears that you also need to include highchart-more.js in your code to get it to work.

**Comment by scania-bootstrap** [comment]
Great!
