### ISSUE TITLE
Text in .form-control[readonly] is barely visible.

### ISSUE THREAD

**Issue by mxuwku** [scania/corporate-ui#41]
**When using .form-control[readonly] the text in the inputfield is barely visible.**

**How it looks**
![image](https://user-images.githubusercontent.com/39794299/41221536-ac2c3a86-6d64-11e8-8159-c62052e99b99.png)

**How it could look:**
![image](https://user-images.githubusercontent.com/39794299/41221763-523e5bfc-6d65-11e8-86bb-d9e0aae29df2.png)

**CSSS**
![image](https://user-images.githubusercontent.com/39794299/41221626-f23fd92e-6d64-11e8-9947-c716e5d96469.png)

**Suggestion: Remove opacity or change it to 1**

**Comment by yuyo2** [comment]
See arrow-class pull request.

**Comment by mmexvr** [comment]
#225

**Comment by mmexvr** [comment]
This is now under visual design, closing it
