### ISSUE TITLE
Fullscreen component in IE doesn't work in sub-navigation

### ISSUE THREAD

**Issue by mmexvr** [scania/corporate-ui#413]
**Describe the bug**<br/>
In IE 11 the fullscreen component doesn't work like it should, when you try and hide the main-navigation when clicking on the sub-navigations fullscreen it only hides the header

**To Reproduce**<br/>
1. Go to http://localhost:1337/examples/more-dynamic2.html#/Eighth
2. Click on subnavigations fullscreen button

**Expected behavior**<br/>
Work same in both browsers 

**Screenshots**<br/>
Chrome
![image](https://user-images.githubusercontent.com/35451568/49149096-7cde5180-f309-11e8-895e-1f0f7178fd54.png)

![image](https://user-images.githubusercontent.com/35451568/49149108-823b9c00-f309-11e8-891a-7ccc2b8ad53d.png)

**Desktop (please complete the following information):**<br/>
 - OS: Windows 10 
 - Browser IE
 - Version 11

**Comment by awinny** [comment]
This will be solved in #417
