### ISSUE TITLE
There is border radius on .nav-justified on the nth-child and not first and last child 

### ISSUE THREAD

**Issue by mmexvr** [scania/corporate-ui#414]
**Version of Corporate-ui**<br/>
3.4.0 

**Describe the bug**<br/>
There is border radius on `.nav-justified` on the nth-child(middle-child) and not first and last child 

**To Reproduce**<br/>
1. Go to https://scania.github.io/corporate-ui-docs/master-branch/developer/bootstrap-original-docs.html#nav
3. Scroll down to `.nav-justified`

**Expected behavior**<br/>
Border-radius should match every li element

**Screenshots**<br/>
![image](https://user-images.githubusercontent.com/35451568/49153596-7d311980-f316-11e8-8b57-21562b6c64d1.png)

**Desktop (please complete the following information):**<br/>
 - OS: Windows 10
 - Browser: Chrome

**Comment by helloimela** [comment]
We will not add new feature in corporate-ui 3. Please look at https://digitaldesign.scania.com/components/navigation 
The design process is stillworking progress. There will be fixes and improvements in the new design in corporate-ui 4
