### ISSUE TITLE
Change icons for full-screen component expand and collapse main navigation.

### ISSUE THREAD

**Issue by scania-bootstrap** [scania/corporate-ui#420]
https://fontawesome.com/icons/expand-alt?style=light
https://fontawesome.com/icons/compress-alt?style=light

**Comment by scania-bootstrap** [comment]
Pull request to be found here: #421

**Comment by helloimela** [comment]
We are not adding new feature to corporate ui 3. If a need rises for this feature, please create a new issue and it will be implemented in corporate-ui 4. Fontawesome is deprecated, and scania icon is used as the default.
