### ISSUE TITLE
Different sizes for nav-pills

### ISSUE THREAD

**Issue by peterpahlman** [scania/corporate-ui#424]
More variations of nav-pills are needed and should inherit the styling from btn-sm and btn-xs, to make nav-pills blend in better in overall UI in more instances.

See attached image for clarification.
<img width="1038" alt="screenshot 2018-12-07 at 14 59 51" src="https://user-images.githubusercontent.com/42805493/49653400-1659e180-fa35-11e8-931f-08984b7c1a20.png">

**Comment by scania-bootstrap** [comment]
Now as a pull request, even though it does not strictly inherit from .btn-sm and btn-xs, rather than beeing the same size:  #446
