### ISSUE TITLE
.input-group and input-group-btn with .btn-default melts into grey background.

### ISSUE THREAD

**Issue by mxuwku** [scania/corporate-ui#43]
**When using `.input-group` and `input-group-btn` with `.btn .btn-default` on grey background it melts into the background.

------------------

**How it looks now**
![image](https://user-images.githubusercontent.com/39794299/41225025-2658a642-6d6e-11e8-95eb-2ab72cda2432.png)

------------------

**Suggestion how it should look**
![image](https://user-images.githubusercontent.com/39794299/41228221-e01ff2fc-6d77-11e8-981c-b7f146f8e403.png)

**Comment by yuyo2** [comment]
We should have a discussion about wich level this should be implemented.

**Comment by yuyo2** [comment]
This should be looked into

**Comment by scania-bootstrap** [comment]
Will be solved by a post it that's on our board right now, temporary form fix. And available in next version:
