### ISSUE TITLE
Bootstrap native is loaded two times in corporate-ui.js

### ISSUE THREAD

**Issue by mmexvr** [scania/corporate-ui#44]
**Describe the bug**
Bootstrap native is loaded two times in corporate-ui

**To Reproduce**
http://localhost:1337 and look at the network tab and search for bootstrap native file 

**Expected behavior**
Bootstrap native should only be loaded once

**Screenshots**
![capture](https://user-images.githubusercontent.com/35451568/41230211-39312fda-6d7f-11e8-8d99-544b9e54c87e.PNG)
![capture2](https://user-images.githubusercontent.com/35451568/41230215-3ae2cfd2-6d7f-11e8-819c-e9b73ff4735b.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 67

**Comment by awinny** [comment]
Fixed in: #57
