### ISSUE TITLE
Add "fullscreen" text besides our fullscreen icon 

### ISSUE THREAD

**Issue by scania-bootstrap** [scania/corporate-ui#447]
Requirements from KS, here's the translations:

https://jira.scania.com/browse/FMS-31402

/Jesper

**Comment by fomekh** [comment]
Proposition of new properties for c-fullscreen component:
- active="false" (default is false)
- text-maximize= "" (default is empty string)
- text-minimize=""  (default is empty string)
@awinny

**Comment by scania-bootstrap** [comment]
Can be fixed at the same time as this one : #421
