### ISSUE TITLE
Brand parameter is not working in IE

### ISSUE THREAD

**Issue by scania-bootstrap** [scania/corporate-ui#45]
**Describe the bug**
When trying to switch brand using the parameter ?brand=XXX it works fine in Chrome but does not work in IE.

Open Chrome
1. Go to https://scania.github.io/corporate-ui-docs/index.html?brand=man

Open  IE11, go to the same page:
1. https://scania.github.io/corporate-ui-docs/index.html?brand=man

**Comment by mmexvr** [comment]
in core.ts `document.addEventListener("DOMContentLoaded", applyBrand); ` isn't triggered in IE

**Comment by mmexvr** [comment]
#126

**Comment by mmexvr** [comment]
Done in #126
