### ISSUE TITLE
Select2 allowClose button is invisible

### ISSUE THREAD

**Issue by adam-scania** [scania/corporate-ui#452]
**Version of Corporate-ui**<br/>
cui 3.5.0, select2 3.5.3

**Describe the bug**<br/>
The close icon of select2 is invisible - but it is there and you can click on it.

**To Reproduce**<br/>
Create an ordinary select2 `<select>` and set the options `allowClear` and `placeholder` accordingly (see documentation http://select2.github.io/select2/)

**Expected behavior**<br/>
I expect to see an X icon or something.

**Screenshots**<br/>
![select2-allow-close](https://user-images.githubusercontent.com/18661799/51747461-de246600-20a9-11e9-97a3-dc01ef68cfc2.png)

**Desktop (please complete the following information):**<br/>
 - OS: Windows 7
 - Browser: Chrome
 - Version: 65

**Comment by scania-bootstrap** [comment]
NOTE. Using "allowClear" on a Select2 container that in on the same row as you're using standard Select will create confusion for the end user.  Why can he close items in one of the dropdowns and why can't he do it in the other dropdowns? Bug?

If the Equipment field is mandtory I would suggest removing "allow clear" as you anyway need to pick anther piece of equipment. 

Back to UX?

**Comment by peterpahlman** [comment]
Definitely agree, if a dropdown field is mandatory there should obviously not be a "Clear all" icon. I'll ask Nicole, who is the preferred UX designer for Service planning, to have an extra look at this!

**Comment by adam-scania** [comment]
The close button is visible now in CUI 3.5.2, albeit misaligned.
![misaligned](https://user-images.githubusercontent.com/18661799/52201106-c9df2680-286a-11e9-9f8a-c0f5579714b8.png)

**Comment by yuyo2** [comment]
#457

**Comment by yuyo2** [comment]
Fixed in #457
