### ISSUE TITLE
Select2 choices

### ISSUE THREAD

**Issue by fomekh** [scania/corporate-ui#454]
**Version of Corporate-ui**<br/>
Version 3.5.2

**Describe the bug**<br/>
Select2 choices: Input text doesn't have padding-left

**To Reproduce**<br/>
Create an ordinary select2 <select> and set the options: multiple, sc-multi-select and placeholder accordingly (see documentation http://select2.github.io/select2/)

**Expected behavior**<br/>
 Expecting a padding-left in input field

**Screenshots**<br/>
![select2-choices](https://user-images.githubusercontent.com/6946108/51903829-6c0b9400-23bd-11e9-93f2-1ee06bde7dff.PNG)

**Desktop (please complete the following information):**<br/>
 - OS: Windows 10
 - Browser: all browser
 - Version: latest version

**Comment by scania-bootstrap** [comment]
@fomekh I'll assign this one to @yuyo2  Martin. Is that OK?

**Comment by yuyo2** [comment]
#457

**Comment by yuyo2** [comment]
Finished in #457
