### ISSUE TITLE
The footer moves when hovering over a nav-item inside the footer

### ISSUE THREAD

**Issue by mmexvr** [scania/corporate-ui#46]
**Describe the bug**
When hovering over a nav-item in the footer the size changes and gets a white space between the bottom of the browser and the footer. In IE

**To Reproduce**
1. Go to a page with nav-item in the bottom
2. Hover over it 
3.. See error that the size changes

**Expected behavior**
The footer shouldn't move

**Screenshots**
![first1](https://user-images.githubusercontent.com/35451568/41413436-69d5791e-6fe3-11e8-874b-ec79db25a9f8.png)

![2](https://user-images.githubusercontent.com/35451568/41413453-7a801a26-6fe3-11e8-9e9e-f5ae0863300c.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser IE
 - Version 11

**Comment by mmexvr** [comment]
Float is causing the issue with a moving footer during hover
`@media (min-width: 992px) {
  :host-context(body.fullscreen) {
    display: none !important;
  }

  :host {

    ::content {

      .dropdown-menu {
        background-color: transparent;
        display: block;
        position: relative;
        border: none;
        box-shadow: none;
        // float: none;

        a {
          font-family: "Scania Sans", Helvetica, Arial, sans-serif;
          font-size: 14px;
          font-weight: bold;
        }
      }
    }
  }
}
`

**Comment by mmexvr** [comment]
Display inline-block might fix this issue, need to test

**Comment by helloimela** [comment]
#426
