### ISSUE TITLE
navbar - styleguide is active at homepage

### ISSUE THREAD

**Issue by carlssons** [scania/corporate-ui#47]
**Describe the bug**
When choosing "HOME" in the navbar "STYLEGUIDE" is active.

**Expected behavior**
"HOME" should be active.

**Screenshots**
![bu1](https://user-images.githubusercontent.com/23013520/41455574-e59a999a-707d-11e8-917e-8b2e53a6a5bf.PNG)

**Desktop**
Chrome

**Comment by scania-bootstrap** [comment]
Fixed. Thank you for reporting!
