### ISSUE TITLE
Button focused decoration

### ISSUE THREAD

**Issue by mxuwku** [scania/corporate-ui#471]
**Is your feature request related to a problem?**
It would feel nice when working only with the keyboard to give the user feedack that he/she is now focusing the button. (good for those who press tab + enter for submitting)

**Describe the solution you'd like**
Implement a button decoration when the button is focused.  

**Describe alternatives you've considered**
No

**Additional context**
Feature is clear enough.

**Comment by helloimela** [comment]
We will not add new feature in corporate-ui 3. Improved button UI is being designed now. Will take this issue into consideration. Please use new design button in corporate-ui 4.

**Comment by helloimela** [comment]
A comprehensive design and interaction for buttons is in progress through Designer's Guild. We will wait for final design before we implement in theme. All implementation will be added in version 4. Issues requesting new feature for Corporate UI 3 will be closed.
