### ISSUE TITLE
Bug - Cookie-message isn't shown in IE11

### ISSUE THREAD

**Issue by mmexvr** [scania/corporate-ui#472]
**Version of Corporate-ui**<br/>
3.5.3

**Describe the bug**<br/>
c-cookie-message component doesn't work in IE 11, because of the support of some methods in IE11 that needs be changed.

**To Reproduce**<br/>
1. Go to static.scania.com in IE11
2. No cookie message shown

**Expected behavior**<br/>
Possibility to see the cookie-message in IE11

**Screenshots**<br/>
![image](https://user-images.githubusercontent.com/35451568/59092566-23875880-8912-11e9-9498-9e069a74b78a.png)

**Desktop (please complete the following information):**<br/>
 - OS: Windows 11
 - Browser: IE
 - Version: 11

**Additional context**<br/>
There is a seperate branch for this solution, but it contains more that is not needed anymore for cookie-message component

**Comment by helloimela** [comment]
We will not add new feature for corporate-ui 3. This issue is from one year ago and no request rises regarding this issue. If you need cookie component, please use our new cookie component that is released in corporate-ui 4 (works in all browsers). https://digitaldesign.scania.com/components/cookie
