### ISSUE TITLE
Visual update to inputs

### ISSUE THREAD

**Issue by mxuwku** [scania/corporate-ui#473]
**Imrpovement needed**<br/>
Inputs needs a visual update.

- [ ] Buttons
- [ ] Labels
- [ ] Badge
- [ ] Input fields
- [ ] Select2
- [ ] Dropdown

Prototype link: https://app.uxpin.com/design-system/06f70c80e5f566b5ec18/ui-patterns/30034

**Describe the improvement**<br/>
Border-radius will be changed from 0px to 3px

**Comment by mmexvr** [comment]
- [x] Buttons
- [x] Labels
- [x] Badge
- [x] Input fields
Done in PR:
#476

**Comment by helloimela** [comment]
We will not add new feature for corporate-ui 3. Please expect update and improvement for forms and fields in corporate-ui 4 releases. This feature is a work in progress now for corporate-ui 4 and is in the design stage. We will close this issue and will create a new issue later when the design is ready.
