### ISSUE TITLE
Bug - fullscreen modal in safari on iphone is conflicting with browser navigation in the button

### ISSUE THREAD

**Issue by mmexvr** [scania/corporate-ui#475]
**Describe the bug**
Issue with the bottom of the modal-fullscreen on iphone in safari. If you have a footer with a btn-block for example then that will be conflicting with the browsers own functionallity and make it impossible to click the button that is behind.

100vh is causing issues on iphone 

**To Reproduce**
1. Go to https://scania.github.io/corporate-ui-docs/corporate-ui/components/#componentModal or any page with fullscreen modal
2. Click on fullscreen modal 
3. Scroll down the modal
4. See the button/footer is behind the browsers own options menu

**Expected behavior**
button should be possible to click

**Screenshots**

**Version of Corporate-ui**
3.5.3

**Smartphone (please complete the following information):**
 - Device: any iphone
 - OS: IOS
 - Browser: Safari

**Comment by helloimela** [comment]
We will not add feature to corporate-ui 3. All components including modal is in the process of being improved and now is in the design stage. We will bring this into account when implementing modal in Corporate-UI 4. Since this problem occurred in Corporate UI 3, we will close this issue.
