### ISSUE TITLE
Corporate-UI not working with @stencil/core 1.3.0

### ISSUE THREAD

**Issue by yuyo2** [scania/corporate-ui#480]
1.	does not work on “Safari and Fire Fox” (testing Fire Fox because looks the same behavior as Safari).
Together with Gustavo Viana we updated @stencil/core 1.0.6 to @stencil/core 1.3.0 and them we received this error:
DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at addStyle (http://localhost:3333/build/core-5c7d4ad1.js:332:40)
    at attachStyles (http://localhost:3333/build/core-5c7d4ad1.js:349:21)
    at updateComponent (http://localhost:3333/build/core-5c7d4ad1.js:1213:9)
    at Array.update (http://localhost:3333/build/core-5c7d4ad1.js:1171:26)
    at consumeTimeout (http://localhost:3333/build/core-5c7d4ad1.js:121:23)
    at flush (http://localhost:3333/build/core-5c7d4ad1.js:144:5)
consoleError @ core-5c7d4ad1.js:65
cava-customer-needs.entry.js:13738 undefined

The error is not clear, Customer Needs was not working and one thing that we did, was stopping using this script
<script src="https://static.scania.com/build/global/3.5.3/js/corporate-ui.js"></script>

If I just load CSS from Scania Corporate UI it works! And all issues from IE11 and Safari was gone.
Using this Corporate UI StencilJs version https://static.scania.com/build/global/4.0.0-alpha.3/corporate-ui.js also works, but CBO needs some extra work.
I guess 3.5.3 Corporate UI is using Polymer library that could conflict with StencilJs new version.

Summary:
@Stencil/core 1.3.0 
•	Fixed all our issues IE11, Safari, Firefox.
•	Contains fixes and features comparing to our current 1.0.6 library version.
•	https://static.scania.com/build/global/3.5.3/js/corporate-ui.js does not work, this is official way to use it right now
may affect new Sales Portal angular version if it’s using this script, and others Scania Apps using this script
•	Work around is Scania Corporate UI StencilJs version but need some extra work on CBO.

@Stencil/core 1.0.6
•	Works with any Corporate UI.
•	Does not work on Safari and Firefox.

**Comment by yuyo2** [comment]
contact person alex.takashi.uezono@scania.com

**Comment by awinny** [comment]
Where can I go to see this error?

I have created a simple stencil setup running corporate ui v3.5.3 and 3.5.3-1.
I saw this error when corporate ui was the first occurring script tag and by simply moving it last it solwed the issue for me.
Good to notice is that the only thing that crashed due to this error seems to be the element ```<stencil-route>```.

**Comment by awinny** [comment]
The setup I have can be found here:
https://github.com/awinny/stencil-cui3/
And a running example can be seen here:
https://awinny.github.io/stencil-cui3/

**Comment by awinny** [comment]
Notice that this is the message that I got locally before moving the script node:

![image](https://user-images.githubusercontent.com/2822573/64853714-48c7e900-d61c-11e9-9700-d633a0f4d867.png)

**Comment by helloimela** [comment]
Please check the solution suggested above (moving script order).
