### ISSUE TITLE
Magnifying glass doesn't show in internet explorer.

### ISSUE THREAD

**Issue by fomekh** [scania/corporate-ui#484]
**Version of Corporate-ui**<br/>
Corporate-ui-v3.5.3-1

**Describe the bug**<br/>
Select2 magnifying glass doesn't show in internet explorer. 

**To Reproduce**<br/>
1. Go to https://fmpnextgen.scania.com
2. Click on Fleet position and click on Map
3. Click on All equipment, and in search box 

**Expected behavior**<br/>
The magnifying glass icon must be shown in search input.

**Screenshots**<br/>

**Desktop (please complete the following information):**<br/>
 - OS: Windows 10
 - Browser: Internet explorer and Edge
 - Version: 11.805....

![Magnifying glass Icon in IE](https://user-images.githubusercontent.com/6946108/68013017-03bf4b00-fc8c-11e9-82ab-0a93f25ceb83.jpg)

**Comment by helloimela** [comment]
Hello, do you still experience this problem?
Can you add more information for example the cause of this problem and possible way to solve it.
Unfortunately we are limited in resources now and we want to focus on the development of our new design system (https://digitaldesign.scania.com/) and corporate-ui v4 which provides more sustainable solution for other projects.
We are supporting all of Scania with general UX/front end, so we no longer can help out with application specific project like we used to.
We would like to ask your help to fix this issue and create a pull request if you think this fix can help the community who uses corporate-ui 3.

Thank you!
