### ISSUE TITLE
Feature - Add toggler for branch preview

### ISSUE THREAD

**Issue by awinny** [scania/corporate-ui#496]
**Describe the solution you'd like**
It could be good to add the possibility to toggle between available branches from the storybook interface. Similar to how its now possible to toggle between releases when you are visiting a CDN page of a released version of corporate cui.

**Additional context**
The release data is fetched from the gh API using their graphql service.
This can be tested by accessing:
https://developer.github.com/v4/explorer
The following query could then be used:
```
query {
  repository(owner:"scania", name:"corporate-ui-dev") {
    refs(refPrefix: "refs/heads/", last: 100) {
      nodes {
        name
      }
    }
  }
}
```

**Comment by helloimela** [comment]
Issue will be closed because we are not using storybook anymore.
