### ISSUE TITLE
Bug - "Issue with Corporate UI in IE for Angular 2+"

### ISSUE THREAD

**Issue by Archiie94** [scania/corporate-ui#503]
**Describe the bug**  
Issue is most likely 
![image](https://user-images.githubusercontent.com/22478268/69315081-07644300-0c36-11ea-9654-8da483ca0ffb.png)

**To Reproduce**   
_Steps to reproduce the behavior:_  
1. Set up Angular 2+ and add Corporate UI.
2. Add polyfills for Angular.
3. Run App in IE. 

**Expected behavior**  
No issue should occur - hence, @awinny recommended compiling everything at first which seems reasonable.

**Screenshots**  
![image](https://user-images.githubusercontent.com/22478268/69315081-07644300-0c36-11ea-9654-8da483ca0ffb.png)

**Version of Corporate-ui**  
4.0.0-beta.2

**Framework and version**  
- Framework: [Angular]
- Version: [~8.2.4]

**Application link**  
Local project - it should occur in **every** angular project.

**Desktop information:**  
 - IE

**Additional context**   
If our team faces this issue, I'm guaranteeing many other teams do/will do it as well. I know it's a beta phase, but I think this step is crucial for business and development teams.

**Comment by helloimela** [comment]
We will close this issue for now, since our test shows that latest beta release works in angular setup in IE.
An example that shows this works in IE will be added to the corporate-ui angular example. See the progress here: https://github.com/scania/corporate-ui-angular/pull/22
