### ISSUE TITLE
Improvement - "corporate ui and scania theme optimization"

### ISSUE THREAD

**Issue by santhoshnagav** [scania/corporate-ui#539]
**Describe current situation**  
We at IXDA use the 'corporate_ui' and 'scania-theme' for chatbot interface. After bundling the corporate_ui and scania_theme package for production the dependencies is almost 9MB which affects the IE and the interface loads much slower for poor internet connection.

**Describe the improvement**  
To reduce the bundled corporate_ui and scania_theme dependency package size.

**Comment by helloimela** [comment]
Hello, thank you for reporting this issue.
Related issue : #502
