### ISSUE TITLE
Wrong z-index on active button in buttons groups 

### ISSUE THREAD

**Issue by mlcdsscania** [scania/corporate-ui#540]
**Describe the bug**  
Active button groups get the wrong z-index (1, should be 0). This results in the active button moving above the c-header while scrolling.

**To Reproduce**   
Create a button group in a corporate-ui page with a c-header
Set a button in the group to be active
Minimize the window enough to get a scroll-bar
Scroll button group towards the c-header

**Expected behavior**  
The complete button group (including an active item) should go below the c-header

![b9fa2b01-7db2-46c6-9ee7-ae92dd34c261](https://user-images.githubusercontent.com/56712181/73357093-fb32dc80-429b-11ea-8b15-0988c5b69f01.jpg)

**Version of Corporate-ui**  
Version 4.0.2

**Desktop information:**  
_Please complete the following information_
 - Chrome 
 - Version 74
 - OS: Win 10

**Comment by mmexvr** [comment]
scania/scania-theme#140
