### ISSUE TITLE
Flash of unstyled content

### ISSUE THREAD

**Issue by mlcdsscania** [scania/corporate-ui#542]
**Describe the bug**  
A flash of unstyled content, which is all to visible for a user, is built into the current version of Corporate UI. Especially if the theme is utilized on a single page application.

**To Reproduce**   
Reload any page with a little content.

**Expected behavior**  
Unstyled content should, normally, not be visible to a user.

**Version of Corporate-ui**  
v4.0.2

**Application link**  
https://codepen.io/corporate-ui/pen/OYmqpr (it's visible on the demo page)

**Desktop information:**  
Chrome 74, Win 10

**Comment by helloimela** [comment]
Additional information:
Related PR #526 
Need to implement solution in CDN usage

**Comment by mmexvr** [comment]
If you have the possibility try and use the npm solution instead :) https://www.npmjs.com/package/corporate-ui

**Comment by mmexvr** [comment]
What are the reason not using to NPM? So we understand the situation more.

**Comment by Ruddy2007** [comment]
> Hi!
> 
> What are the reason not using to NPM? So we understand the situation more.
> 
> Sorry for the late answer

I guess saying "not able to use" is not a good way to put it. Should be more of we shouldn't be forced to use NPM. This project has instructions to use it via CDN, should this not be working? I doubt anyone would use it via CDN given this breaking bug.

**Comment by mmexvr** [comment]
Thanks for the answer!

Is there is a reason why CDN is prefered over NPM ? Because we recommend NPM over CDN. Maybe we should be more clear on that from our end! There are more benefits with NPM.  

The reason for asking this, we are investigating the use of CDN, trying the gather feedback. 

Are using any framework right now in your project? (Angular,react..)

**Comment by Ruddy2007** [comment]
> Thanks for the answer!
> 
> Is there is a reason why CDN is prefered over NPM (If you move away from corporate-ui 3) ? Because we recommend NPM over CDN for v4. Maybe we should be more clear on that from our end! There are more benefits with NPM.
> 
> The reason for asking this, we are investigating the use of CDN in v4, trying the gather feedback.
> 
> Are using any framework right now in your project? (Angular,react..)

No problem. 

I guess using a 1 liner `<script />` just seems simpler than using NPM. Our sites vary from simple MVC, Angular JS, Angular and possibly Blazor in the future. We had some issues working with NPM to start but have overcome them so we should be able to use it. 

But from my point of view using CDN should be a valid option for all developers and the Corporate UI should support it without a breaking bug such as this one. 

I think it would be nice to see a bit more documentation around the NPM side of things. Why you recommend it over CDN etc... maybe a more detailed guide about using NPM.

**Comment by mmexvr** [comment]
Thanks for the anwser again!

I agree on all points reagarding we should support it in a better, if we have it. I will esclate it to be higher priority. 

I'm working right now on a easier documentation for implementing CUI 4. 

Just a small note regarding the npm recommendation.
CDN is easier to use, but it isn't hard to use NPM it is as easy. Its like importing any other framework/pluggin/addon. CDN makes it a resources that is hosted by us, which we control. While using a NPM package makes much much easier to use and control on your end. You are not dependent on our CDN connection. 

But agree, we should add more regarding this


Good feedback!

**Comment by Ruddy2007** [comment]
Good job @helloimela and @mmexvr ! 👍
