### ISSUE TITLE
Bug - Special Language - characters -  breaks the cookie popup

### ISSUE THREAD

**Issue by matssonadam** [scania/corporate-ui#547]
**Describe the bug**  
_A clear and concise description of what the bug is._
When we are authoring the Category headings such as "Necessary cookies", "Targeting cookies" etc in a special character, the component seems to break. 
![image](https://user-images.githubusercontent.com/49981098/76217354-91024580-6212-11ea-9817-811aec25eb53.png)

![image](https://user-images.githubusercontent.com/49981098/76217741-4208e000-6213-11ea-991f-0b5c872838c8.png)

____________________________________________________________________________________________________

**To Reproduce**   
_Steps to reproduce the behavior:_  
1. Go to https://aem-pre-author.scania.com/content/scanianoe/bg/bg/home/admin/sitesettings.html?wcmmode=disabled
2. Click on 'настройки за бисквитки'
3. Scroll up to error
4. See error (no visible cookie groups) Compare to:
https://aem-pre-author.scania.com/content/scanianoe/uk/en/home/admin/sitesettings.html?wcmmode=disabled

**Expected behavior**  
_A clear and concise description of what you expected to happen._
User expects to be able to add any language that Scania operates in such as Russian, Finnish, Swedish, Japanese, Korean, Chinese etc
**Screenshots**  
_If applicable, add screenshots to help explain your problem._
![image](https://user-images.githubusercontent.com/49981098/76216473-f0f7ec80-6210-11ea-9415-6839b9eb4672.png)
Here it works:
![image](https://user-images.githubusercontent.com/49981098/76216498-fce3ae80-6210-11ea-95fe-a343e0c6833a.png)

**Version of Corporate-ui**  
 _E.g 4.0.0-alpha.1_

static.scania.com/cds/awinny/corporate-ui/dist/corporate-ui/corporate-ui.js

static.scania.com/cds/awinny/scania-theme/1.0.2-7/dist/scania-theme.js

**Framework and version**  
_If you use any specific framework please provide information_
- Framework: [e.g Angular]
- Version: [ e.g 6 ]
No
**Application link**  
_Provide link if possible_  
- [https://example.com](/)
Links provided above

**Desktop information:**  
_Please complete the following information_
 - Browser [e.g. chrome, safari] - Chrome - Firefox, Edge, Internet explorer 11, Safari
 - Version [latest
 - OS: [e.g. Windows 10] yes

**Additional context**   
_Add any other context about the problem here._
Important to be fixed as soon as possible since we are going live internationally tomorrow 2020-03-10

**Comment by awinny** [comment]
This has been resolved in:
https://github.com/scania/corporate-ui/commit/bcb4fa498d62388ad69d9fc534031653ff544c8c
It has been made accessible under a temporary url and will be merged to master when we have adjusted the other available component to follow the same setup.

**Comment by matssonadam** [comment]
Works great, closing ticket!
