### ISSUE TITLE
Bug - MAC - Chrome + Safari + Edge Chronium Cookie banner issue

### ISSUE THREAD

**Issue by matssonadam** [scania/corporate-ui#548]
**Describe the bug**  
When using a MAC computer and different browsers such as Chrome - Safari - Edge Chromium the cookie banner breaks:
![image](https://user-images.githubusercontent.com/49981098/76434434-f478a880-63b5-11ea-94d0-01149c1a17db.png)

**To Reproduce**   
_Steps to reproduce the behavior:_  
1. Go to any scania site in incognito mode (need to get cookie message) on a MAC machine
2. Scroll down to bottom of the page - The cookie message will show as the picture above. Without any "I accept" or "Cookie settings" buttons.

**Expected behavior**  
To be able to accept and open cookies settings, also to have the same design as on other PCs
**Screenshots**  
See above

**Application link**  
_Provide link if possible_  
https://www.scania.com/se/sv/home.html

**Desktop information:**  
_Please complete the following information_
New Edge Chromium on MAC and also Safari.
 
Med Chrome Version (80.0.3987.132 (Officiell version) (64 bitar) on MAC 

**Additional context**   
_Add any other context about the problem here._

**Comment by awinny** [comment]
We have done a investigation on this and we could not reproduce this problem.

What we tested was a **Macbook pro** with the following browsers:
- Safari 13.0.5
- Chrome 80.0.3987.132 (64 bits)
- Firefox 74.0 (64 bits)

We would need to know more about the circumstances.

Things that could be tested or checked:
- Was the cache cleared
- Was the page accessed from VPN
- Was a special setup used, like Citrix

**Comment by helloimela** [comment]
Issue will be closed. Please report a new issue if problem appears.
