### ISSUE TITLE
Bug - "Cookie is missing an expiry date"

### ISSUE THREAD

**Issue by lchkux** [scania/corporate-ui#549]
**Describe the bug**  
scania.com uses the cookie component from Corporate UI. The component is live now in production and we have noticed that cookie is getting removed every time a user closes the browser. That means the cookie is session based or an expiry date is not set.

**To Reproduce**   
1. Go to www.scania.com
2. Click on  Accept button in the cookie banner
3. Cookies are enabled
4. Close the browser
5. Reopen the browser and navigate to scania.com
6. Cookie banner pops up again

**Expected behavior**  
Cookie should have an expiry date of 1 year set and cookie banner should not show up again unless and until the user clears the cookies from the browser 

**Screenshots**  
![image](https://user-images.githubusercontent.com/62105927/76528760-9a3d1d80-6471-11ea-8940-e8fff23d854e.png)

**Application link**  
www.scania.com

**Comment by awinny** [comment]
I have now added options for configuring the cookie.
The fix can be seens here:
https://github.com/scania/corporate-ui/commit/0ca88112f1ed127c15fc07273bb2da9f8593bd19

**Comment by mmexvr** [comment]
Been merged and release in lastest pre-release
