### ISSUE TITLE
Bug - "The Scania Sans stylesheet contains other rules than @font-face"

### ISSUE THREAD

**Issue by patrickchan-staygold** [scania/corporate-ui#553]
**Describe the bug**  
The [Scania Sans stylesheet](https://static.scania.com/resources/fonts/scania-sans/scania-sans.css) contains css rules for .teaser-title and .bootstrap #slider-wrapper

**To Reproduce**   
1. Go to [Scania Sans stylesheet](https://static.scania.com/resources/fonts/scania-sans/scania-sans.css)
2. Scroll pass the @font-face rules
3. Other types of rules should not in this file

**Expected behavior**  
File should only contain @font-face rules.

**Application link**  
- [Scania Sans stylesheet](https://static.scania.com/resources/fonts/scania-sans/scania-sans.css)

**Comment by mmexvr** [comment]
Good catch!

This isn't something we can really fix in that file, since it might be affecting some application that are using older corporate-ui/scania-bootstrap. But agree with the solution!

Thanks for the feedback!
