### ISSUE TITLE
Bug - code example component in IE not working as expected

### ISSUE THREAD

**Issue by helloimela** [scania/corporate-ui#557]
**Describe the bug**  
Color is missing in code-example component in IE & uneccessary text is added at the top of the component

**To Reproduce**   
_Steps to reproduce the behavior:_  
1. Open Digital Design System site in IE
2. Go to components > alert
3. check code-example
4. See color is missing and uneccessary text added

**Expected behavior**  
Should look like this:
![image](https://user-images.githubusercontent.com/1199101/79333872-8cbafd80-7f1f-11ea-81f7-a0c2ab99fb3b.png)

**Screenshots**  
How it is look like in IE
![image](https://user-images.githubusercontent.com/1199101/79333910-a0666400-7f1f-11ea-9c4a-658d85a29d67.png)

**Version of Corporate-ui**  
 4.1.0

**Framework and version**  
_If you use any specific framework please provide information_
- Framework: Angular
- Version: 8

**Application link**  
_Provide link if possible_  
https://digitaldesign.scania.com/home

**Desktop information:**  
_Please complete the following information_
 - BrowserIE
 - Version 11
 - OS:  Windows 10

**Comment by mmexvr** [comment]
In FF font-size is bigger
