### ISSUE TITLE
Wrong in example at static.scania.com

### ISSUE THREAD

**Issue by sssaff** [scania/corporate-ui#56]
**Describe the bug**
On the page https://scania.github.io/corporate-ui-docs/developer/bootstrap-original-docs.html#forms there is an example of a checkbox. Here is the code:
< label >
< input type="checkbox" > Check me out
< span >< /span >
 < /label >

But this will not work. The span needs to be above the text. This is a working example:
< label>
< input type="checkbox" > 
< span>< /span>
Check me out
 < /label>

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by scania-bootstrap** [comment]
Fixed!
