### ISSUE TITLE
Improvement - "Adding new features for table component"

### ISSUE THREAD

**Issue by gustavookamoto** [scania/corporate-ui#575]
While I was implementing the table component, I realise some improvements that would be good to have it:
- Hover optinon with event emitter (as edit and delete options)
- Clear fields with "cross-icon" inside inputs.
- Code review

![image](https://user-images.githubusercontent.com/55094504/89941561-9284cf00-dbf1-11ea-8606-97f0560cb966.png)

Fixes: #576

**Comment by helloimela** [comment]
Hello, could you provide more information about the features you want to add ?
Where is the hover will occured? Is it in the button or in a table row?
How is the expected UI after this new addition added? Maybe a screenshot will help.
Thanks!

**Comment by mmexvr** [comment]
agree with @helloimela,
Is it possible to add some more information overall why this is needed? 

Try and follow the template we provide for the feature request :) 

Thanks!

**Comment by gustavookamoto** [comment]
Hello!

1. Hover option with event emitter
Created this option as a optional feature for the developers that want to add an action when click on the row. If the developers want to just use the hover class without any events, thy can just add the class. It's an optional feature.

2. Clear fields with "cross-icon" inside inputs.
When the filter input is filled, with the 1st version, the user have to clear the field manually. With this new option, when there's some value on the input field, the filter icon on the right will be replaced with a cross icon, and when clicks on it, it will erase the input and filter again without lose the values from other fields if it's filled.
