### ISSUE TITLE
Bug - Problems to implement c-table with pre-release version

### ISSUE THREAD

**Issue by gustavookamoto** [scania/corporate-ui#577]
I'm trying to use the new pre-release versions for corporate-ui and scania-theme installing via NPM, but when I execute the project, the component isn't building properly.
I've tried to install in many different ways, but it's not working.

**To Reproduce**   
uninstal the current version from your project and install both packages (corporate-ui 4.1.2-1 / scania-theme 1.1.3-1) via npm.

![image](https://user-images.githubusercontent.com/55094504/90425376-057cc280-e096-11ea-85a8-d05318fde27f.png)

**Comment by helloimela** [comment]
Hello @gustavookamoto , could you provide more details, in which framework are you working on?
I tried to reproduce in simple HTML script import, and also in angular, and it works fine.

![image](https://user-images.githubusercontent.com/1199101/90486474-4843a680-e139-11ea-9130-5871f41cb7aa.png)

**Comment by helloimela** [comment]
Do you receive any error message on the console window?

**Comment by gustavookamoto** [comment]
Hello, I'm using angular 9 and it's not displaying any error messages. I just uninstalled the old versions and installed using npm.

![image](https://user-images.githubusercontent.com/55094504/90517521-e173bc80-e13b-11ea-80ef-de33c4fa44e1.png)

![image](https://user-images.githubusercontent.com/55094504/90517554-f18b9c00-e13b-11ea-8225-53de8b2207ec.png)

**Comment by helloimela** [comment]
Now I got the same error when trying in Angular 9. It seems like the styling from the theme is not rendered in a correct manner. Could be a problem with loading order or the way the view is rendered has changed in Angular 9 causing issues with CSS adopted stylesheet technique that we have in CUI. 🤔  @mmexvr

**Comment by helloimela** [comment]
Did some test and apparently it's an initiation problem. The line below shows the value of `style` is null _sometimes_. 
https://github.com/scania/corporate-ui/blob/984267950f5dcc799ae7bf39cf904049f0f3501b/src/helpers/themeStyle.ts#L12
