### ISSUE TITLE
Problem with Highchart

### ISSUE THREAD

**Issue by sssaff** [scania/corporate-ui#59]
**Describe the bug**
Highchart area cuts in half in certain situations. Visual bug.

**To Reproduce**
1. Go to 'http://sesoco3300/foma/'
2. Look at graph. It fills out the whole div
3. Click on 'Edit values'-tab
4. Check checkbox "Last forecast" 
5. Click back on "Graph"-tab
6. Loot at error
7. Resizeing the browser window resets the graph back to normal

**Expected behavior**
The graph should always fill out the whole div

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by scania-bootstrap** [comment]
This is acutally a HighCharts issue but here is the solution:

function chartResize() {
    if(!!$.prototype.highcharts) {
        $(".highcharts-container").parent().each(function() {
            var chart = $(this).highcharts(); // target the chart itself
            chart.reflow() // reflow that chart
        });
    }
}


Call chartResize() whenever you need to reflow.

/Jesper
