### ISSUE TITLE
Include HighCharts Reflow function in Corporate UI

### ISSUE THREAD

**Issue by scania-bootstrap** [scania/corporate-ui#60]
function chartResize() {
    if(!!$.prototype.highcharts) {
        $(".highcharts-container").parent().each(function() {
            var chart = $(this).highcharts(); // target the chart itself
            chart.reflow() // reflow that chart
        });
    }
}

**Comment by awinny** [comment]
Maybe we should add this to the highsharts component?
Its this a issue in latest highshart if not maybe we should consider updating to latest version?

**Comment by scania-bootstrap** [comment]
We're getting rid of HighCharts all in all.
