### ISSUE TITLE
IE: Top right Scania Icon hiding the right aligned menu items on Scrolling

### ISSUE THREAD

**Issue by shaheer-scania** [scania/corporate-ui#69]
Open any portal using corporate-ui in IE, and having top menu items aligned right
Scroll vertically
Now you can see that the top level Scania Icon is hiding the menu item

Its happening only in IE, working in Chrome

**Comment by scania-bootstrap** [comment]
What corporate-ui.js version?

**Comment by shaheer-scania** [comment]
@scania-bootstrap version is  2.5.0

**Comment by scania-bootstrap** [comment]
Scania Bootstrap is only a subset of Corporate UI so I hope you're using corporate-ui.js?
The menu is re-worked in version 3.0.0 so please try to upgrade to that one and see if the problem persists:

https://github.com/scania/corporate-ui/releases

/Jesper

**Comment by mmexvr** [comment]
Closing this issue for now, inactive
