### ISSUE TITLE
Corporate UI adds container class to component, breaking the layout if hosted in narrow column

### ISSUE THREAD

**Issue by scania-bootstrap** [scania/corporate-ui#7]
Container has a fixed with and that makes component break the design if hosted in a 2 column, or more, layout. See the Alert below.

![image](https://user-images.githubusercontent.com/10209902/40648663-446d45dc-632f-11e8-840b-99861d1d5d85.png)

**Comment by awinny** [comment]
This is due to the fullbleed flag default to true.
Making all components adding a wrapped container and by setting fullbleed to true this will automatically be fixed.
@scania-bootstrap Should we change this behaivor?

**Comment by mmexvr** [comment]
I will close this for now, reopen if needed
