### ISSUE TITLE
Excessive white-space in `.btn-link` and `.scania-icon-*`

### ISSUE THREAD

**Issue by scania-bootstrap** [scania/corporate-ui#8]
Button links and icons have excessive white-space.  

![image](https://user-images.githubusercontent.com/10209902/40648836-ac458796-632f-11e8-8542-be17d22d80dc.png)

**Comment by scania-bootstrap** [comment]
I the idea with the btn class is to get the link aligned with text on buttons. The Icons has to much padding, as deliverd from Brand Union. Should be fixed.

**Comment by awinny** [comment]
@scania-bootstrap please explain further. Are we talking about the carret or plus icon?

**Comment by adam-scania** [comment]
The purple area is superfluous

**Comment by adam-scania** [comment]
The icons have a similar problem. Ideally they should be as small as possible while still containing the bitmap, right?

**Comment by scania-bootstrap** [comment]
@adam-scania This is a kind of VÉRY old due to the fact that it's cumbersome to fix, at least when it comes to the icons.

For the .btn-linkl, there should be no white space if not use togheter with the .btn class that's actually are adding the padding. Can you please try to remove the .btn class and check how it works out for you. For some links, we do not want the ´´<a>´´´behaviour why we're using the button classes.

When it comes to Icons, as we are moving to Font Awesome 5, I would like to close this issue for now.
