### ISSUE TITLE
Imports INSIDE components has not been updated to the new structure

### ISSUE THREAD

**Issue by scania-bootstrap** [scania/corporate-ui#85]
![image](https://user-images.githubusercontent.com/10209902/42698484-54303e68-86be-11e8-9d5a-2d4ccfd35bcc.png)

**Comment by scania-bootstrap** [comment]
In this case there is no longer any folder called Contact.

**Comment by scania-bootstrap** [comment]
I think you temporarily MOVED all components that was not updated to another location. So they need to be updated before moving them back into the repository. Or did I remember wrong?

**Comment by mmexvr** [comment]
Correct, I moved them My bad! :-)

But everyone of those components that was moved haven't been made into the structure we are using right now. Maybe we should make a new issue that we should create them in our current structure. So it shoudn't matter right now for this issue regarding the problem of incorrect paths

**Comment by mmexvr** [comment]
This issue need be redefined.

Should we add the components back and create them in polymer structure or wait for the new technolgy
