### ISSUE TITLE
Collapse/Expand icon in Mobile Navigation only visible for current active nav-item

### ISSUE THREAD

**Issue by scania-bootstrap** [scania/corporate-ui#90]
**Describe the bug**
I belive it should be possible to expand and collapse all sub-navigations once you're in the mobile navigation.

**To Reproduce**
On your mobile phone, or in a narrow web browser:
1. Go to https://scania.github.io/corporate-ui-docs/developer/
2. Notice that only Web Applications has an collapse icon to the right.
3. Go to https://scania.github.io/corporate-ui-docs/styleguide/
4. Notice that only Style Guide has an collapse icon to the right.

**Expected behavior**
I think all sub navigations should be represented by expand and collapse icons?

**Comment by awinny** [comment]
This should work simply by adding the sub-navigation to all items that should have chilldrens.

**Comment by scania-bootstrap** [comment]
This one was wrongly reported as it works as long as all submenus appear in the main menu navigation structure for that particular page.

Closing.
