### ISSUE TITLE
Nav items and social icons in footer are not correctly laid out. Scania name should be editable. 

### ISSUE THREAD

**Issue by scania-bootstrap** [scania/corporate-ui#91]
**Describe the bug**
Social icons are currently stacked on top of each other, should be horizontally aligned.

Nav items, after expanding the dropup meny, should be centered align.

**To Reproduce**
Lok at this page in mobile view: https://scania.github.io/corporate-ui-docs/index-aws.html#

**Comment by mmexvr** [comment]
#127

**Comment by mmexvr** [comment]
Still need some fix for dropdown menu

**Comment by mmexvr** [comment]
Still need improvement for dropdown menu

**Comment by mmexvr** [comment]
Will create a new issue regarding dropup menu in footer component

**Comment by mmexvr** [comment]
#161
