### ISSUE TITLE
Javascript section of UX Library needs to be upgraded to reflect Bootstrap Native

### ISSUE THREAD

**Issue by scania-bootstrap** [scania/corporate-ui#94]
Click Bootstrap Javascript here: https://scania.github.io/corporate-ui-docs/developer/bootstrap-original-docs.html#top

Should  acutally display this information: https://thednp.github.io/bootstrap.native/

**Comment by mmexvr** [comment]
#387 
#297

**Comment by mmexvr** [comment]
Done
