### ISSUE TITLE
Web Components should be displayed 

### ISSUE THREAD

**Issue by scania-bootstrap** [scania/corporate-ui#95]
Web components listing works fine:
https://scania.github.io/corporate-ui-docs/component/

Clicking on an individual component, it does not show.

Also, use the corporate-ui JS method for showing the same components as the current version in use for Corporate UI.,

**Comment by mmexvr** [comment]
Is this related with the IE browser or chrome also?

It seems to work in chrome for me with version 3.1.0-cf

**Comment by scania-bootstrap** [comment]
I fixed this before vaccation.
