### ISSUE TITLE
History in Safari for iPhone is not displaying <c-main-content> and <c-corporate-footer>

### ISSUE THREAD

**Issue by scania-bootstrap** [scania/corporate-ui#96]
This occurs in Corporate UI version 3.1.0 on iPhone X IOS 11.4 but possibly other devices and versions as well.

To reproduce:
Go to the UX Library and navigate around:

- Go to the Style Guide
- Then go to the Colours page
- Then go to the Variables page

Now, try to go back to the Style Guide by using the browsers back icon (arrow left).

**Comment by awinny** [comment]
This might not be a Iphone specific problem, I think I have seen this in IE as well?

**Comment by awinny** [comment]
@scania-bootstrap Is this still an issue?
I have tried to reproduce this, seems to work on my desktop in mobile mode at least.

**Comment by scania-bootstrap** [comment]
Will double check.

**Comment by helloimela** [comment]
All related contents in UX Library will be moved to https://digitaldesign.scania.com/
We will not add fixes to UX Library.
